/**
 * FZK Haus (Karlsruhe) as energy-engine input — the Clinic's and
 * Schependomlaan's sibling, and the first of the three with no placeholders
 * at all: every envelope figure below is either read from the committed
 * manifest or from a `ThermalTransmittance` / `IfcMaterialLayer` the file
 * states directly on the element.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  WHAT MAKES THIS FILE DIFFERENT FROM ITS TWO SIBLINGS
 *
 *  The Clinic states no U-value anywhere (zero `IfcThermalTransmittanceMeasure`).
 *  Schependomlaan states 97 of them and every one is a documented zero — an
 *  authoring artefact, not a value, so its U-values are SOLVED from layer
 *  sets instead. FZK Haus states 33 — one per wall, window, door and slab —
 *  and every one is a real, non-zero, plausible number (exterior wall 0.4,
 *  window 1.4, roof 0.3 W/m²K). This file therefore does the opposite of
 *  Schependomlaan's: the STATED per-element U is the primary source, and the
 *  layer-solved figure (`FZK_HAUS_WALL_ASSEMBLY_SOLVED`) is the disclosed
 *  cross-check, not the other way round. See `A-STATED-U-PRIMARY`.
 *
 *  The one place that reverses again is the ground slab. `Bodenplatte`
 *  states ThermalTransmittance 0.4 — an ordinary air-to-air U — and using it
 *  as the ground-facing U would repeat the Clinic's own headline defect (a
 *  slab on grade has no air-to-air U; ISO 13370 applies, not ISO 6946). So
 *  the ground floor is the one element where the stated 0.4 is DISCLOSED but
 *  NOT used, and `slabOnGroundUValue` runs instead on the slab's own stated
 *  layer (0.2 m reinforced concrete, no insulation board at all). See
 *  `A-GROUND-STATED-U-NOT-AIR-TO-AIR`.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * Same discipline as `bs-medical-dental-clinic-energy.ts`: four exports
 * (`FZK_HAUS_RECIPE`, `FZK_HAUS_MATERIALS`, `FZK_HAUS_MEASURED_ENVELOPE`,
 * `FZK_HAUS_ASSUMPTIONS`), no `_PENDING_MEASUREMENTS` — there is nothing
 * pending.
 *
 * Sources:
 *   - `public/reference-buildings/fzk-haus/manifest.json`, generated by
 *     `scripts/build-reference-building.mjs` (`FZK_HAUS` config) from KIT/IAI's
 *     `AC20-FZK-Haus.ifc` (unrestricted use, attribution required — see the
 *     config comment and `docs/04_Agent-Handoffs/2026-09-06-gallery-consistency-visuals-brief.md`).
 *   - `public/reference-buildings/fzk-haus/spaces.json`, 7 IfcSpace rows.
 *   - `public/reference-buildings/fzk-haus/openings.json`, 13 opening rows.
 */

import type { BuildingRecipe, FloorSpec } from "@/lib/procedural/types";
import type { MaterialProperties } from "@/lib/material-types";
import { getRecipe } from "@/lib/procedural/recipe";
import { slabOnGroundUValue, slabOnGroundUValueRange } from "@/lib/energy-standards/ground-coupling";
import { calculateAssembly } from "@/lib/energy-standards/assembly";
import { genericMaterialById } from "@/lib/energy-standards/materials";

const lambda = (id: string): number => {
  const material = genericMaterialById(id);
  const value = material?.conductivityWPerMK;
  if (value === undefined) {
    throw new Error(`generic material ${id} states no conductivity`);
  }
  return value;
};

// ── Measured geometry, from the committed manifest ────────────────────────

/**
 * Two storeys. `Dachgeschoss` states `floorToFloorHeightM: 0` — it is the
 * top storey, so there is no next datum to subtract from — and its real
 * ceiling is the pitched roof: the Galerie space's own closed solid tops out
 * at 6.087 m (`measureSpaceMeshes`, cross-checked against the OG gable
 * walls' own stated max height 3.387 m + the 2.7 m datum). ROOF_DATUM_M
 * below is that ridge line, not a storey height.
 */
const GROUND_FLOOR_HEIGHT_M = 2.7;
const RIDGE_HEIGHT_M = 6.09;

export const FZK_HAUS_STOREYS = Object.freeze({
  groundFloor: Object.freeze({ id: "storey-erdgeschoss", nameDe: "Erdgeschoss", elevationM: 0, floorToFloorM: GROUND_FLOOR_HEIGHT_M, floorAreaSqm: 101.39, spaceCount: 6 }),
  /**
   * The Galerie (mezzanine gallery under the roof) at 107.16 m² GrossFloorArea
   * — larger than its own floor slab (Slab-033, 99.84 m² net) and than either
   * roof deck's projected shadow (71.5 m² each). Plausible for an open
   * gallery over a double-height room; taken as the file's own stated
   * quantity, not independently re-derived. See the config comment in
   * `scripts/build-reference-building.mjs` (`FZK_HAUS.spacesNote`).
   */
  attic: Object.freeze({ id: "storey-dachgeschoss", nameDe: "Dachgeschoss", elevationM: GROUND_FLOOR_HEIGHT_M, floorToFloorM: RIDGE_HEIGHT_M - GROUND_FLOOR_HEIGHT_M, floorAreaSqm: 107.16, spaceCount: 1 }),
  roofDatumM: RIDGE_HEIGHT_M,
});

export const FZK_HAUS_TOTAL_FLOOR_AREA_SQM = 208.55;

/** `areas.exteriorWallNetSqm` — 8 exterior walls, opening area already removed. */
const EXTERIOR_WALL_NET_SQM = 136.28;

/**
 * `areas.exteriorWallByOrientationSqm`. This building is NOT axis-aligned:
 * `manifest.orientation.trueNorthDeg` is 50°, so every one of its 8 walls
 * falls in a diagonal sector (NE/SE/SW/NW) and all four true cardinals (N/E/S/W)
 * are exactly 0 — the opposite pattern from Schependomlaan, whose diagonals
 * were the empty ones. See `A-NORTH-ROTATED`.
 */
export type WallSector = "N" | "NE" | "E" | "SE" | "S" | "SW" | "W" | "NW";

export const FZK_HAUS_WALL_BY_SECTOR_SQM: Readonly<Record<WallSector, number>> =
  Object.freeze({
    N: 0,
    NE: 39.56,
    E: 0,
    SE: 28.85,
    S: 0,
    SW: 37.23,
    W: 0,
    NW: 30.63,
  });

/** `areas.glazingApertureSqm` — 11 windows, real `OverallWidth × OverallHeight`. */
const GLAZING_APERTURE_SQM = 23.6;

export const FZK_HAUS_GLAZING_BY_SECTOR_SQM: Readonly<Record<WallSector, number>> =
  Object.freeze({
    N: 0,
    NE: 5.8,
    E: 0,
    SE: 4.8,
    S: 0,
    SW: 5.8,
    W: 0,
    NW: 7.2,
  });

/** `areas.exteriorDoorSqm` — 2 exterior doors (Haustuer, Terrassentuer); 3 interior doors excluded. */
const EXTERIOR_DOOR_SQM = 6.8;

export const FZK_HAUS_DOOR_BY_SECTOR_SQM: Readonly<Record<WallSector, number>> =
  Object.freeze({
    N: 0,
    NE: 0,
    E: 0,
    SE: 4.77,
    S: 0,
    SW: 2.03,
    W: 0,
    NW: 0,
  });

/** `areas.roofProjectedSqm` / `areas.roofSurfaceSqm` — Dach-1 + Dach-2, 30° pitch. */
const ROOF_PROJECTED_SQM = 143;
const ROOF_SURFACE_SQM = 171.13;

/** `areas.groundSlabSqm` / `areas.groundPerimeterM` — Bodenplatte, one slab, no holes. */
const GROUND_SLAB_SQM = 120;
const GROUND_PERIMETER_M = 44;

// ── The envelope this file hands the engine ───────────────────────────────

export const FZK_HAUS_MEASURED_ENVELOPE = Object.freeze({
  exteriorWallNetSqm: EXTERIOR_WALL_NET_SQM,
  exteriorWallByOrientationSqm: FZK_HAUS_WALL_BY_SECTOR_SQM,
  exteriorWallBelowRoofSqm: 85.66,
  exteriorWallAboveRoofSqm: 50.62,
  northAssumed: false,
  glazingApertureSqm: GLAZING_APERTURE_SQM,
  glazingByOrientationSqm: FZK_HAUS_GLAZING_BY_SECTOR_SQM,
  exteriorDoorSqm: EXTERIOR_DOOR_SQM,
  exteriorDoorByOrientationSqm: FZK_HAUS_DOOR_BY_SECTOR_SQM,
  /** Opaque wall + glazing + doors: the whole exterior wall plane. */
  grossWallSqm: EXTERIOR_WALL_NET_SQM + GLAZING_APERTURE_SQM + EXTERIOR_DOOR_SQM,
  roofProjectedSqm: ROOF_PROJECTED_SQM,
  roofAreaSqm: ROOF_SURFACE_SQM,
  groundSlabSqm: GROUND_SLAB_SQM,
  groundPerimeterM: GROUND_PERIMETER_M,
  /** `areas.conditionedVolumeGrossM3` — inside the air barrier. */
  conditionedVolumeGrossM3: 636.66,
  /**
   * `areas.roomVolumeNetM3` — the 7 space solids, EACH FROM ITS OWN STATED
   * `NetVolume` quantity. The Galerie's Qto also states a `GrossVolume` of
   * 428.64 m³ (= 107.16 m² × a flat 4.0 m nominal "Height" property) that
   * exceeds even the room's own bounding box (362.92 m³) — an authoring
   * artefact caught by this repo's net-must-not-exceed-gross guard, fixed at
   * the extractor level (`quantityIndex` in `ifc-envelope.mjs`, 2026-09-06)
   * by preferring the quantity NAMED `NetVolume` over whichever
   * `IfcQuantityVolume` happens to come first in the set. `NetVolume`
   * (217.53 m³) matches the space's own closed-solid mesh volume to 5
   * decimal places. See `A-GALERIE-GROSS-VOLUME-ARTEFACT`.
   */
  roomVolumeNetM3: 470.82,
  provenance: Object.freeze({
    exteriorWallNetSqm: "manifest",
    exteriorWallByOrientationSqm: "manifest",
    exteriorWallBelowRoofSqm: "manifest",
    exteriorWallAboveRoofSqm: "manifest",
    glazingApertureSqm: "manifest",
    glazingByOrientationSqm: "manifest",
    exteriorDoorSqm: "manifest",
    exteriorDoorByOrientationSqm: "manifest",
    grossWallSqm: "derived_from_manifest",
    roofProjectedSqm: "manifest",
    roofAreaSqm: "manifest",
    groundSlabSqm: "manifest",
    groundPerimeterM: "manifest",
    conditionedVolumeGrossM3: "manifest",
    roomVolumeNetM3: "manifest",
  }),
});

// ── Constructions: STATED per-element U is primary; layers are the cross-check ──

/**
 * The exterior wall's own material layer: 0.3 m of `Leichtbeton` (lightweight
 * concrete), mapped to the standards library's autoclaved-lightweight-concrete
 * row (`st-lwc`, λ 0.16). Solved at ISO 6946 vertical surface resistances:
 * R = 0.3/0.16 + 0.13 + 0.04 = 2.045 → U 0.489 W/m²K — 22 % WORSE than the
 * file's own stated 0.4. This file uses the STATED value (`A-STATED-U-PRIMARY`)
 * and keeps the solved one here so the disagreement is visible rather than
 * silently favouring whichever number was computed second.
 */
export const FZK_HAUS_WALL_ASSEMBLY_SOLVED = calculateAssembly(
  [{ id: "Leichtbeton (exterior leaf)", thicknessM: 0.3, conductivityWPerMK: lambda("st-lwc") }],
  "horizontal",
);
export const FZK_HAUS_WALL_U_STATED = 0.4;

/**
 * The roof deck's material layer is named `Solid` — an ArchiCAD placeholder,
 * not a real material identity — so there is NOTHING to solve a U from. The
 * file's stated 0.3 W/m²K is the ONLY usable figure for this element; there
 * is no second reading to disagree with it.
 */
export const FZK_HAUS_ROOF_U_STATED = 0.3;

/**
 * `Bodenplatte`'s own layer: 0.2 m reinforced concrete (`st-rc`, λ 2.3), NO
 * insulation board of any kind. R_f = 0.2/2.3 = 0.087 m²K/W — the resistance
 * ISO 13370 wants, EXCLUDING surface resistances, which is why the file's own
 * stated air-to-air 0.4 is not used here (`A-GROUND-STATED-U-NOT-AIR-TO-AIR`).
 */
const GROUND_FLOOR_RESISTANCE_M2KW = 0.2 / lambda("st-rc");
export const FZK_HAUS_GROUND_STATED_AIR_TO_AIR_U = 0.4;

/** Exterior wall thickness at the slab edge, `Wand-Ext-ERDG-*`'s own stated Width. */
const WALL_THICKNESS_AT_SLAB_M = 0.3;

const groundInputs = {
  areaSqm: GROUND_SLAB_SQM,
  exposedPerimeterM: GROUND_PERIMETER_M,
  wallThicknessM: WALL_THICKNESS_AT_SLAB_M,
  floorResistanceM2KPerW: GROUND_FLOOR_RESISTANCE_M2KW,
} as const;

/**
 * 120 m² over 44 m: B' = 120 / (0.5 × 44) = 5.45 m. With no insulation at
 * all under the slab (R_f 0.087), this sits deep in ISO 13370's
 * uninsulated regime.
 */
export const FZK_HAUS_GROUND_FLOOR = slabOnGroundUValue(groundInputs);
export const FZK_HAUS_GROUND_FLOOR_RANGE = slabOnGroundUValueRange(groundInputs);

// ── Window-to-wall ratio: real per-sector ratios, relabelled onto the engine's four keys ──

/**
 * ONE whole-building ratio, on all four cardinal keys — NOT the four
 * measured per-sector ratios, even though this building's glazing genuinely
 * is measured per sector. `heat-loss.ts`'s `meanWindowToWallRatio` weights
 * by `walls[].surfaceArea`, which is NET opaque wall, while each per-sector
 * ratio's own denominator is that sector's GROSS wall (wall+glazing+door) —
 * they do not cancel, so handing the four real ratios in would move the
 * engine's answer for no reason connected to what was actually measured.
 * Measured on this building (bim-83 found the same shape on the Duplex,
 * where the effect is 10x larger — see A-WWR-ENGINE-MEAN):
 *
 *   weighted-by-net-wall mean   0.141506   (uniform: 0.141585)
 *   window area                22.996 m²  against a measured 23.6 m²
 *
 * The gap is tiny here (FZK Haus's four sector ratios span 0.125-0.190,
 * against the Duplex's 0.10-0.37), but the mechanism is identical and the
 * fix is the same: one ratio, against gross, is the only figure that
 * reproduces the building's own measured aperture exactly — see
 * `A-WWR-ENGINE-MEAN`. The real per-sector figures stay available in
 * `FZK_HAUS_WALL_BY_SECTOR_SQM` / `_GLAZING_BY_SECTOR_SQM` / `_DOOR_BY_SECTOR_SQM`
 * for the legend, which is the only current consumer that can say anything
 * with four different numbers.
 */
export const FZK_HAUS_WWR_UNIFORM =
  FZK_HAUS_MEASURED_ENVELOPE.glazingApertureSqm / FZK_HAUS_MEASURED_ENVELOPE.grossWallSqm;

// ── The recipe: shape and metadata only ───────────────────────────────────

const floors: FloorSpec[] = [
  { floorNo: 1, label: "1F — Erdgeschoss", type: "above", y: 0, height: GROUND_FLOOR_HEIGHT_M, isGroundFloor: true, useCode: "01000" },
  { floorNo: 2, label: "2F — Dachgeschoss (Galerie)", type: "above", y: GROUND_FLOOR_HEIGHT_M, height: RIDGE_HEIGHT_M - GROUND_FLOOR_HEIGHT_M, isGroundFloor: false, useCode: "01000" },
];

/** Not a measurement — see `A-NO-FOOTPRINT`, same shape as Schependomlaan's. */
const FOOTPRINT_SIDE_M =
  Math.round(Math.sqrt(FZK_HAUS_STOREYS.groundFloor.floorAreaSqm) * 100) / 100;

/**
 * Era 2000-2009: the file states NO construction date anywhere (it is KIT's
 * "Simple Phantasy Building", built for validation research, not a real
 * project) — this is a placed GUESS, informed only by the magnitude of the
 * stated U-values (wall 0.4, roof 0.3 W/m²K sit close to German
 * WSchV 1995 / early EnEV targets). As with Schependomlaan, the era's ONLY
 * effect is on cosmetic recipe defaults: every thermal value that matters is
 * overridden below by the file's own stated numbers. See `A-ERA-UNDATED`.
 */
const defaults = getRecipe("21", "2000-2009", "01000", false);

export const FZK_HAUS_RECIPE: BuildingRecipe = {
  ...defaults,
  era: "2000-2009",
  buildingName: "FZK Haus",
  address:
    "Eggenstein-Leopoldshafen, Germany (derived from IfcSite RefLatitude/RefLongitude, " +
    "49.100435N 8.436539E — Forschungszentrum Karlsruhe / KIT Campus North, the model's " +
    "own naming institution. IfcPostalAddress states no town; the place name is read " +
    "from the coordinate, not from a stated address).",
  footprintWidth: FOOTPRINT_SIDE_M,
  footprintDepth: FOOTPRINT_SIDE_M,
  officialFloorAreaSqm: FZK_HAUS_TOTAL_FLOOR_AREA_SQM,
  floors,
  totalHeight: RIDGE_HEIGHT_M,
  wallThickness: WALL_THICKNESS_AT_SLAB_M,
  mainPurpsCd: "01000",
  strctCd: "21",
  siteWidth: FOOTPRINT_SIDE_M,
  siteDepth: FOOTPRINT_SIDE_M,
  measuredEnvelope: {
    planAreaSqm: FZK_HAUS_MEASURED_ENVELOPE.groundSlabSqm,
    wallLengthM: FZK_HAUS_MEASURED_ENVELOPE.groundPerimeterM,
    grossWallAreaSqm: FZK_HAUS_MEASURED_ENVELOPE.grossWallSqm,
    roofAreaSqm: FZK_HAUS_MEASURED_ENVELOPE.roofAreaSqm,
    volumeM3: FZK_HAUS_MEASURED_ENVELOPE.conditionedVolumeGrossM3,
    derivedFloorAreaSqm: FZK_HAUS_TOTAL_FLOOR_AREA_SQM,
    basis:
      "FULLY MEASURED — no placeholder in this building. Wall, glazing, door, roof, " +
      "ground and volume areas are read from the FZK Haus IFC by " +
      "scripts/build-reference-building.mjs (name-matched exterior wall walk against " +
      "stated NetSideArea, IfcSpace stated quantities, per-element roof shadows, the " +
      "ground slab's shadow union). U-values are the file's own stated " +
      "ThermalTransmittance per element, not solved from generic-library layers, " +
      "except the ground floor, where ISO 13370 replaces the file's air-to-air figure.",
  },
};

// ── Materials ─────────────────────────────────────────────────────────────

const wallLayers = [
  { name: "Leichtbeton (lightweight concrete)", thickness: 0.3, thermalConductivity: lambda("st-lwc"), density: 500, specificHeat: 1000 },
];

const wall = (orientation: "N" | "S" | "E" | "W", surfaceArea: number) => ({
  orientation,
  uValue: FZK_HAUS_WALL_U_STATED,
  rValue: 1 / FZK_HAUS_WALL_U_STATED,
  layers: wallLayers,
  thermalBridge: 0,
  surfaceArea,
});

export const FZK_HAUS_MATERIALS: MaterialProperties = {
  source: "ifc-model",
  confidence: "measured",
  codeYear: 2005,
  envelope: {
    // Cardinal keys required by MaterialProperties; this building's real
    // walls are all diagonal (NE/SE/SW/NW) — see A-NORTH-ROTATED. Total
    // wall area is preserved via `surfaceArea` summing to EXTERIOR_WALL_NET_SQM
    // across the four required entries, split proportionally to the two
    // storeys' real orientation shares rather than invented.
    walls: [
      wall("N", FZK_HAUS_WALL_BY_SECTOR_SQM.NE),
      wall("E", FZK_HAUS_WALL_BY_SECTOR_SQM.SE),
      wall("S", FZK_HAUS_WALL_BY_SECTOR_SQM.SW),
      wall("W", FZK_HAUS_WALL_BY_SECTOR_SQM.NW),
    ],
    roof: {
      uValue: FZK_HAUS_ROOF_U_STATED,
      layers: [
        { name: "Solid (roof deck, unidentified material)", thickness: 0.2, thermalConductivity: 0.2 / FZK_HAUS_ROOF_U_STATED, density: 1000, specificHeat: 1000 },
      ],
      solarReflectance: 0.3,
      emissivity: 0.9,
      greenRoofCoverage: 0,
    },
    groundFloor: {
      uValue: FZK_HAUS_GROUND_FLOOR.uValueWPerM2K,
      layers: [
        { name: "Stahlbeton (reinforced concrete)", thickness: 0.2, thermalConductivity: lambda("st-rc"), density: 2400, specificHeat: 880 },
      ],
      groundContactResistance: 0,
    },
    windows: {
      uValue: 1.4,
      shgc: 0.6,
      vlt: 0.7,
      glassType: "double",
      coating: "none",
      gasFill: "air",
      frameMaterial: "wood",
      airLeakageRate: 0.3,
      shadingCoefficient: 0.69,
      windowToWallRatio: {
        N: FZK_HAUS_WWR_UNIFORM,
        S: FZK_HAUS_WWR_UNIFORM,
        E: FZK_HAUS_WWR_UNIFORM,
        W: FZK_HAUS_WWR_UNIFORM,
      },
    },
    foundation: {
      perimeterInsulationUValue: 0,
      groundTemperature: 13.5,
      moistureBarrier: "none",
    },
    airtightness: {
      ach50: 6,
      equivalentLeakageArea: 0,
      testMethod: "estimated",
    },
  },
  hvac: {
    heating: { systemType: "individual", fuelType: "gas", efficiency: 0.87, capacity: 0 },
    cooling: { systemType: "split", efficiency: 3.5, capacity: 0 },
    ventilation: { type: "natural", heatRecoveryEfficiency: 0, airflowRate: 0 },
    dhw: { systemType: "gas-boiler", efficiency: 0.85, storageVolume: 0 },
  },
  lighting: {
    lightingPowerDensity: 6,
    controlType: "manual",
    lampType: "led",
  },
  renewable: {
    solarPV: { installed: false, capacity: 0, panelType: "monocrystalline", tiltAngle: 0, orientation: 0, area: 0 },
    solarThermal: { installed: false, collectorArea: 0, efficiency: 0 },
    geothermal: { installed: false, systemType: "closed-loop", cop: 0 },
  },
  occupancy: {
    occupancyDensity: 0.04,
    weekdaySchedule: [1, 1, 1, 1, 1, 1, 0.9, 0.7, 0.4, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.6, 0.8, 0.9, 1, 1, 1, 1, 1],
    weekendSchedule: [1, 1, 1, 1, 1, 1, 1, 0.9, 0.8, 0.7, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.7, 0.8, 0.9, 1, 1, 1, 1, 1],
    internalHeatGain: 3,
    hotWaterDemand: 40,
  },
};

// ── Every assumption, named ───────────────────────────────────────────────

export type FzkHausAssumption = Readonly<{ id: string; assumes: string; why: string }>;

export const FZK_HAUS_ASSUMPTIONS: readonly FzkHausAssumption[] = Object.freeze([
  // ── The building's own selling point, and its one reversal ─────────────
  { id: "A-STATED-U-PRIMARY", assumes: "Wall (0.4), window (1.4), exterior door (1.4) and roof (0.3 W/m²K) U-values are the file's own stated IfcPropertySingleValue 'ThermalTransmittance', used directly rather than solved from a generic-material layer substitution.", why: "This is the first reference building here where every relevant element states a real, non-zero, per-element U — the Clinic states none and Schependomlaan's 97 are all a documented zero. The wall's layer-solved cross-check (FZK_HAUS_WALL_ASSEMBLY_SOLVED, U 0.489) disagrees with the stated 0.4 by 22%, and the roof's material is named 'Solid' — an ArchiCAD placeholder with no identifiable conductivity at all, so for the roof there is nothing to solve a second reading from. The stated value is closer to the file's own intent than a generic-library substitution would be, and is used everywhere except the ground floor." },
  { id: "A-GROUND-STATED-U-NOT-AIR-TO-AIR", assumes: "The ground floor's engine U is the ISO-13370-solved value (see FZK_HAUS_GROUND_FLOOR), NOT the file's own stated 0.4 W/m²K on Bodenplatte.", why: "A stated ThermalTransmittance on a ground slab is an ordinary air-to-air figure — exactly the Clinic's own headline defect (a slab on grade has no air-to-air U; the ground assumes a semi-infinite soil path, ISO 6946 does not model it). Using 0.4 directly here would repeat that error in a new building. The slab's own stated layer (0.2 m reinforced concrete, R_f 0.087 m²K/W, no insulation board of any kind) feeds ISO 13370 instead, at the slab's real measured area (120 m²) and exposed perimeter (44 m)." },
  { id: "A-GALERIE-GROSS-VOLUME-ARTEFACT", assumes: "The Galerie's net room volume is 217.53 m³ (its own stated NetVolume, exact match to its closed-solid mesh), not the 428.64 m³ its Qto's GrossVolume states (= 107.16 m² x a flat, apparently manually-set 4.0 m 'Height' property, disconnected from the actual pitched-roof geometry).", why: "The build script's net-must-not-exceed-gross guard caught this: 428.64 > 362.92 (the space's own bounding-box-derived gross), and 362.92 itself exceeds the space's true closed-solid volume of 217.53. Traced to scripts/lib/ifc-envelope.mjs's quantityIndex(), which took the FIRST IfcQuantityVolume in the set — GrossVolume, listed before NetVolume in this file's Qto_SpaceBaseQuantities — the same 'whichever comes first' shape this codebase has already named and fixed for wall areas (statedWallAreas matching NetSideArea by name). Fixed 2026-09-06 by preferring a quantity NAMED NetVolume where one exists; the fallback for every other building's Qto, which states no such name, is unchanged. Verified: rebuilding the Clinic before/after the fix is byte-for-byte identical (the fix is a no-op there); rebuilding Schependomlaan moves its roomVolumeNetM3 from 2530.05 to 2497.61 (real IfcSpace rows in that file also had a same-named NetVolume this repo was not reading) — that rebuild is not shipped by this lane; it is main-coordinator's call when Schependomlaan's committed artifacts are next regenerated." },

  // ── Constructions ────────────────────────────────────────────────────
  { id: "A-WALL-LEICHTBETON-LAMBDA", assumes: "'Leichtbeton' (lightweight concrete) maps to the standards library's autoclaved-lightweight-concrete row (st-lwc, λ 0.16 W/mK, 500 kg/m³).", why: "The IFC material name carries no conductivity of its own — GENERIC_MATERIALS has no exact 'Leichtbeton' row, and st-lwc is the nearest category and density match. Used only for the disclosed cross-check (A-STATED-U-PRIMARY); it does not drive the engine's wall U." },
  { id: "A-ROOF-MATERIAL-UNIDENTIFIED", assumes: "The roof deck's 0.2 m 'Solid' material layer has no identifiable conductivity and no cross-check is attempted.", why: "'Solid' is an ArchiCAD generic-object placeholder name, not a material specification — unlike the wall's 'Leichtbeton' or the slab's 'Stahlbeton', it names no physical substance. Inventing a λ to back-solve the stated 0.3 W/m²K would launder a made-up material as measured; the layer thickness (0.2 m, real) is recorded and the material identity is not." },
  { id: "A-GROUND-NO-INSULATION", assumes: "The ground slab (Bodenplatte) has exactly one stated layer — 0.2 m reinforced concrete — and no insulation board beneath it.", why: "The file's own IfcMaterialLayerSet for this slab (setId 34527) lists one layer, Stahlbeton 65690 at 0.2 m. Nothing else is added: an uninsulated slab is a real, if dated, German construction detail, and inventing an insulation layer the file does not state would move the ground U in the flattering direction with no basis." },
  { id: "A-SOIL", assumes: "Soil conductivity 2.0 W/m·K under the slab (ISO 13370's own default).", why: "Soil is never in a drawing set, and this is the same default used for the Clinic and Schependomlaan, for the same reason." },

  // ── Openings ──────────────────────────────────────────────────────────
  { id: "A-GLAZING-SHGC", assumes: "SHGC 0.60, VLT 0.70, double glazing, no low-e coating, air fill.", why: "The file states window U (1.4 W/m²K, whole-window) and dimensions, and nothing about the glass composition. 1.4 is consistent with an ordinary (non-low-e) double unit rather than an HR++ unit, which typically reaches 1.1-1.2 — the SHGC/VLT/coating fields follow that reading rather than assuming a better pane than the U-value implies." },
  { id: "A-DOORS", assumes: "The 6.80 m² of exterior door leaves (Haustuer, Terrassentuer) are priced at their own stated U 1.4 W/m²K, same as the windows.", why: "Unlike Schependomlaan and the Clinic, this file states a door U directly — Haustuer and Terrassentuer each carry ThermalTransmittance 1.4, identical to the windows' figure. Used as stated; no substitution needed." },

  // ── Orientation ───────────────────────────────────────────────────────
  { id: "A-NORTH-ROTATED", assumes: "manifest.orientation.trueNorthDeg (50°) is the file's own stated true-north rotation, and this building's 8 exterior walls are genuinely all in the diagonal octants (NE/SE/SW/NW) with all four true cardinals at exactly 0.", why: "Unlike Schependomlaan (TrueNorth unstated, defaulting to the schema's 0°/cardinal-aligned reading) and the Clinic, this file states a real rotation and web-ifc's orientation pass reports it. Every interface this energy path hands numbers to — MaterialProperties.envelope.walls, ReferenceBuildingEnergyInputs.wallByOrientationSqm — only has four CARDINAL slots (N/S/E/W), so the true NE/SE/SW/NW split is relabelled onto them (NE→N, SE→E, SW→S, NW→W) for structural compatibility. THIS IS A KNOWN, UNFIXED GAP, not a resolved one: `reference-energy.tsx`'s orientation legend (Lane 2's file) renders these four keys captioned by their compass letter, so on this building's page that legend will show 'North: 39.56 m²' for what is genuinely this building's NORTHEAST wall — the number is right, the compass label is not, which is exactly the class of defect AGENTS.md names 'the label lies while the number is right'. Flagged to main-coordinator/Lane 2 rather than fixed here: fixing it needs the Orientation type and the legend widened to 8 sectors, which touches a file this lane does not own. The true, honestly-labelled split lives in FZK_HAUS_WALL_BY_SECTOR_SQM / FZK_HAUS_GLAZING_BY_SECTOR_SQM / FZK_HAUS_DOOR_BY_SECTOR_SQM. See A-WWR-ENGINE-MEAN." },
  { id: "A-WWR-ENGINE-MEAN", assumes: "All four cardinal ratios handed to MaterialProperties are the single whole-building 0.1416 (23.6 / 166.68), not the four measured per-sector ratios.", why: "Measured through the real engine on 2026-09-06, following bim-83's finding on the Duplex that the obvious next step — hand `meanWindowToWallRatio` the real per-sector split — is wrong. The weight is `walls[].surfaceArea`, which is NET opaque wall, while each ratio's own denominator is that sector's GROSS wall (wall+glazing+door); they do not cancel. Weighted by net wall this building's four real ratios (0.1279/0.1249/0.1287/0.1903) give a mean of 0.141506 and a window area of 22.996 m² against the measured 23.6 m² — small here (this building's four ratios span only 0.125-0.190) but the same-shaped error bim-83 measured at 10x the size on the Duplex, whose ratios span 0.10-0.37. Weighting instead by GROSS wall reproduces the aperture exactly — Σ(rᵢ·grossᵢ)/Σgrossᵢ ≡ Σglazing/Σgross is an identity, not a coincidence — but gross is not what `surfaceArea` is used for elsewhere (it sizes the wall-insulation retrofit measure as opaque wall). So one ratio is used, against gross, and it reproduces the measured aperture by construction; the four measured per-sector ratios stay in FZK_HAUS_WALL_BY_SECTOR_SQM/_GLAZING_BY_SECTOR_SQM/_DOOR_BY_SECTOR_SQM for the legend, the only present consumer that can do anything with four different numbers." },

  // ── Systems and people — the file states none of this ───────────────
  { id: "A-HVAC", assumes: "Individual gas heating at η 0.87, split-system cooling at COP 3.5, natural ventilation, gas DHW at η 0.85 — the repo's own 01000 (단독주택) row (korean-building-codes.ts).", why: "The file has no MEP model of any kind — no HVAC, electrical or plumbing IFC exists for this building at all (unlike the Clinic and the Duplex, both of which carry real services models). Rather than invent a residential system from nothing, this takes the Korean code table's own single-family-house row, exactly as A-CLIMATE already substitutes a Korean climate for this building's real German site." },
  { id: "A-LPD", assumes: "Lighting power density 6 W/m², manual control, LED lamps — the repo's own 01000 row.", why: "The file states no lighting load and no luminaire. Same substitution pattern as Schependomlaan's A-LPD, using this building's own nearest Korean use-code row rather than inventing a figure." },
  { id: "A-OCCUPANCY", assumes: "0.04 persons/m² (the 01000 row), residential day/night schedules, internal gain 3 W/m², hot water 40 L/person/day.", why: "No occupancy data exists in a coordination model with no services and no COBie schedules. At 0.04 persons/m² over 208.55 m² this reads about 8.3 people — plausible for a single-family test house sized around 5-6 rooms (Schlafzimmer, Buero, Wohnen, Küche, Bad, Flur, Galerie)." },
  { id: "A-AIRTIGHT", assumes: "ACH50 = 6 (a dated, uninsulated-envelope default), no blower-door result exists.", why: "No airtightness test or stated infiltration rate exists in the file. 6 ACH50 is a conservative figure for construction consistent with the stated U-values (wall 0.4, uninsulated ground slab) — closer to WSchV-1995-era airtightness expectations than a modern Passivhaus-adjacent figure. The engine divides by 20 to reach a natural rate of 0.30 h⁻¹, the same conversion this repo already regression-tests." },
  { id: "A-VOLUME", assumes: "The ventilation term uses the gross conditioned volume, 636.66 m³, not the 470.82 m³ the corrected room solids sum to.", why: "The file states no single building-wide volume; both figures are measured (the gross from floor area x storey height, with the Galerie's own solid as the top storey's own solid since the storey has nothing above it; the net from each space's own stated NetVolume). Gross is what an infiltration rate is defined against — everything inside the air barrier." },
  { id: "A-CLIMATE", assumes: "A Korean climate (Seoul) for a German building.", why: "The site coordinate is genuinely stated and precise (49.100435N 8.436539E, to the arc-second, plotting to Forschungszentrum Karlsruhe / KIT Campus North) — unlike the Clinic (unknown site) this building's location is known but, like Schependomlaan, unusable: the engine's regional table is Korean-only. Karlsruhe is milder than Seoul in winter and has a smaller cooling load in summer, so a Seoul climate should push this building's modelled demand up on both counts." },

  // ── Scope and shape ──────────────────────────────────────────────────
  { id: "A-NO-FOOTPRINT", assumes: "The recipe's footprint is a 10.07 m square (sqrt of the ground storey's 101.39 m²).", why: "Same shape as Schependomlaan's A-NO-FOOTPRINT: the manifest states no plan outline as a polygon, only per-room extents, so no true footprint shape is recovered. Nothing in the energy path reads it — measuredEnvelope short-circuits envelopeQuantities." },
  { id: "A-ERA-UNDATED", assumes: "Era 2000-2009, chosen from the magnitude of the file's own stated U-values, not from any date the file states.", why: "AC20-FZK-Haus is KIT/IAI's 'Simple Phantasy Building' — a validation test house, not a dated real project. It carries no construction-year field. The era selects only cosmetic Korean code-table recipe defaults for anything not overridden below, and every U-value, WWR and airtightness figure here IS overridden explicitly by this file's own numbers, so the era decides nothing that reaches a kWh figure." },
  { id: "A-STRUCTURE-CODE", assumes: "Structure code 21 (철근콘크리트, RC) as the nearest Korean register category for a lightweight-concrete house.", why: "The register's structure vocabulary has no row for autoclaved lightweight concrete specifically; RC is the nearest concrete-family code, closer than a masonry code (22-25) given the wall's material is a cast/panel concrete product rather than fired brick or block." },
]);
