// src/lib/reference-buildings/inferred-mep.ts
//
// Building services for reference models whose SOURCE contains none.
//
// Five of the nine gallery models ship a single architectural IFC and nothing
// else. Their `serviceLayers` is empty by FACT, not by omission — the build
// script says so in as many words for FZK Haus: "No services model of any kind
// (no MEP, electrical or plumbing IFC exists for this building)".
//
// So anything drawn here is an INFERENCE, never evidence. It is generated by
// the same canonical MEP engine the twin uses (`src/lib/mep`), from:
//
//   - the model's MEASURED bounding box, taken from the loaded GLB, and
//   - the storey elevations and floor-to-floor heights the manifest STATES,
//     which web-ifc read out of the source file.
//
// Both inputs are real. The network laid out between them is not: no duct in
// these buildings has been surveyed, and a viewer must be told that before it
// reads a pipe as a fact. `INFERRED_MEP_LAYER` carries that sentence, and
// `reference-building-workspace.tsx` renders `serviceLayers[].note` for
// exactly this purpose — "a layer that is NOT the model's own geometry says
// so here".
//
// This file must never write into `manifest.serviceLayers`. Those entries
// describe published source artifacts with byte lengths and element counts;
// an inferred network has neither, and merging the two would destroy the
// distinction the gallery exists to preserve.

import { getRecipe } from "@/lib/procedural/recipe";
import { planMepSystemsForRecipe } from "@/lib/mep";
import type { MepModel } from "@/lib/mep/types";
import type { BuildingRecipe, FloorSpec } from "@/lib/procedural/types";
import type { BuildingEra } from "@/lib/material-types";

/** A storey as the manifest states it, read from the source IFC. */
export interface ManifestStorey {
  id: string;
  name: string;
  elevationM: number;
  floorToFloorHeightM: number;
  floorAreaSqm?: number;
}

/** Measured extent of the loaded model, in metres. */
export interface MeasuredFootprint {
  widthM: number;
  depthM: number;
}

/**
 * The layer descriptor for generated services.
 *
 * Deliberately NOT shaped like a `ReferenceServiceLayer`: it has no
 * `byteLength`, no `elements` and no `sha256`, because it is not a published
 * artifact and must not be able to sit in a list of them by accident.
 */
export const INFERRED_MEP_LAYER = {
  id: "inferred-mep",
  ko: "추정 설비 (원본 아님)",
  en: "Inferred services (not from source)",
  note: {
    ko: "이 모델의 원본 파일에는 설비(MEP) 도면이 없습니다. 여기 보이는 배관·덕트·단말은 건축 형상에서 규칙 기반으로 생성한 추정 배치이며, 실제 설치된 설비가 아닙니다. 실측 근거로 인용할 수 없습니다. 생성기는 각 층을 직육면체로 가정하므로, 경사 지붕 건물에서는 최상층 배관이 지붕면을 통과해 보일 수 있습니다.",
    en: "This model's source files contain no MEP drawing. The runs, ducts and terminals shown here are a rule-based layout generated from the architectural geometry — not equipment that was surveyed or installed. Do not cite it as measured evidence. The generator assumes each storey is a rectangular prism, so on a pitched-roof building the topmost runs can appear to pass through the roof plane.",
  },
} as const;

/**
 * The era a generated network assumes.
 *
 * Service sizing and routing rules are era-indexed. None of these five models
 * states a Korean permit date, so there is nothing to classify: this is a
 * stated assumption of the generator, not a reading of the source. It is
 * exposed rather than buried so the viewer can name it.
 */
export const INFERRED_MEP_ERA: BuildingEra = "2000-2009";

/**
 * 주용도코드 for the MEP rules, mapped from the manifest's `useType`.
 *
 * Only affects which service rule-set the generator picks. An unmapped type
 * falls back to the generic table rather than guessing a specific use — the
 * same failure mode `classifyEraExplicit` exists to prevent on the energy
 * path, applied here.
 */
export function mainPurposeCodeFor(useType: string | undefined): string {
  switch (useType) {
    case "office_building":
      return "14000";
    case "single_family_house":
      return "01000";
    case "apartment_building":
      return "02000";
    case "hotel":
      return "15000";
    default:
      return "14000";
  }
}

/**
 * Turn stated storeys into the floor list the MEP planner reads.
 *
 * A storey whose stated floor-to-floor height is 0 — FZK Haus's Dachgeschoss
 * is one — would collapse the plenum the planner routes in. Such a storey
 * inherits the height of the one below it, and when there is no such storey
 * the whole model is refused rather than defaulted: a network laid out in a
 * zero-height void is worse than no network.
 */
export function floorsFromStoreys(storeys: readonly ManifestStorey[]): FloorSpec[] | null {
  if (storeys.length === 0) return null;

  const ordered = [...storeys].sort((a, b) => a.elevationM - b.elevationM);
  const floors: FloorSpec[] = [];
  let lastGoodHeight = 0;

  for (const [index, storey] of ordered.entries()) {
    let height = storey.floorToFloorHeightM;

    if (!(height > 0)) {
      // Prefer the next storey's elevation delta — it is still measured.
      const next = ordered[index + 1];
      const delta = next ? next.elevationM - storey.elevationM : 0;
      height = delta > 0 ? delta : lastGoodHeight;
    }
    if (!(height > 0)) return null;
    lastGoodHeight = height;

    floors.push({
      floorNo: index + 1,
      label: storey.name || `${index + 1}F`,
      type: "above",
      y: storey.elevationM,
      height,
      isGroundFloor: index === 0,
    });
  }

  return floors;
}

/**
 * The plate the network is laid out on.
 *
 * The model's bounding box is the wrong answer on its own: it includes the
 * roof overhang, so on FZK Haus a network planned on it ran outside the walls
 * and through the eaves. The storey's STATED floor area is the better figure —
 * web-ifc read it from the source — so the box supplies only the aspect ratio
 * and the area supplies the size.
 *
 * Falls back to the raw box when no area is stated, which is honest: a plate
 * that is too generous is visible, whereas a fabricated area would not be.
 */
export function plateFromAreaAndAspect(
  size: MeasuredFootprint,
  floorAreaSqm: number | undefined,
): MeasuredFootprint {
  const { widthM, depthM } = size;
  if (!(floorAreaSqm && floorAreaSqm > 0) || !(widthM > 0) || !(depthM > 0)) {
    return size;
  }
  const boxArea = widthM * depthM;
  if (!(boxArea > 0) || floorAreaSqm >= boxArea) return size;
  // Preserve the measured aspect, shrink to the measured area.
  const scale = Math.sqrt(floorAreaSqm / boxArea);
  return { widthM: widthM * scale, depthM: depthM * scale };
}

export interface InferredMepInput {
  storeys: readonly ManifestStorey[];
  footprint: MeasuredFootprint;
  useType?: string;
}

/**
 * Plan services for a model that states none.
 *
 * Returns `null` when the stated geometry cannot support a layout — an absent
 * network is an honest answer, a fabricated one is not.
 */
export function planInferredMep(input: InferredMepInput): MepModel | null {
  const floors = floorsFromStoreys(input.storeys);
  if (!floors) return null;

  const ground = [...input.storeys].sort((a, b) => a.elevationM - b.elevationM)[0];
  const { widthM, depthM } = plateFromAreaAndAspect(input.footprint, ground?.floorAreaSqm);
  if (!(widthM > 0) || !(depthM > 0)) return null;

  const mainPurpsCd = mainPurposeCodeFor(input.useType);
  const base = getRecipe("일반철골구조", INFERRED_MEP_ERA, mainPurpsCd) as BuildingRecipe;
  const totalHeight = floors.reduce((sum, floor) => sum + floor.height, 0);

  const recipe: BuildingRecipe = {
    ...base,
    footprintWidth: widthM,
    footprintDepth: depthM,
    // The measured box is the outer extent; no interior ring is known, and a
    // guessed one would move every riser. Leave it absent so the planner uses
    // the rectangle it was given.
    footprintPolygon: undefined,
    floors,
    totalHeight,
    mainPurpsCd,
    era: INFERRED_MEP_ERA,
  };

  return planMepSystemsForRecipe(recipe);
}
