/**
 * The published face of a reference building.
 *
 * Generated by `scripts/build-reference-building.mjs` into
 * `public/reference-buildings/<id>/manifest.json` and read from there at
 * request time — never bundled. A card's figures and the model it opens must
 * come from the same file, or the two drift the first time extraction changes
 * and nothing notices.
 */
export type ReferenceBuildingManifest = Readonly<{
  kind: "bimfit_reference_building_manifest";
  schemaVersion: 1;
  id: string;
  name: Readonly<{ ko: string; en: string }>;
  summary: Readonly<{ ko: string; en: string }>;
  useType: string;
  licence: string;
  /** Rendered wherever the building is shown — a CC BY condition. */
  attribution: string;
  sourceUrl: string;
  generatedAt: string;
  sourceFiles: readonly Readonly<{
    role: string;
    fileName: string;
    sha256: string;
    byteLength: number;
  }>[];
  counts: Readonly<{
    storeys: number;
    spacesTotal: number;
    spacesFloor: number;
    assemblies: number;
    externalElements: number;
    exteriorWalls: number;
  }>;
  areas: Readonly<{
    /** Floor only. The denominator of every intensity figure. */
    totalFloorAreaSqm: number;
    /** The model's own area-plan total. Recorded, never divided by. */
    areaPlanTotalSqm: number;
    exteriorWallNetSqm: number;
    exteriorWallBelowRoofSqm: number;
    exteriorWallAboveRoofSqm: number;
    /**
     * Wall area per compass sector, summing to `exteriorWallNetSqm`.
     *
     * A monthly method needs this and a degree-day one does not: ISO 13790
     * computes solar gain per orientation, and the same 2,150.3 m² total
     * describes a very different building depending which way it faces.
     */
    exteriorWallByOrientationSqm?: Readonly<Record<string, number>>;
    /**
     * Inside the air barrier: floor-counting rooms as floor area × storey
     * floor-to-floor, plus OPEN TO BELOW voids as their own solids. What an
     * infiltration rate is quoted against, and what the ventilation term
     * multiplies. Absent on a manifest built before 2026-09-04 17:35.
     */
    conditionedVolumeGrossM3?: number;
    /** The space solids summed as modelled — they stop at the ceilings. Not the engine's volume. */
    roomVolumeNetM3?: number;
    volumeNote?: string;
  }>;
  /** Every level the file declares, lowest first, including datums with no rooms. */
  storeys?: readonly Readonly<{
    id: string;
    name: string;
    elevationM: number;
    /** 0 for the top level — nothing above it to measure to. */
    floorToFloorHeightM: number;
    spaceCount: number;
    floorAreaSqm: number;
    ref: string;
  }>[];
  /** Sibling file with one row per IfcSpace — see `ReferenceBuildingSpace`. */
  spacesFile?: string;
  /**
   * Layer stacks as the model states them, outside-in.
   *
   * Names and thicknesses only, because the file states nothing else — no
   * conductivity, no U-value. Solving these into U-values is the job of
   * `constructions.ts`, deliberately outside this manifest: every λ is an
   * assumption, and this document reports only what the model says.
   */
  assemblies?: readonly Readonly<{
    id: string;
    name: string;
    totalThicknessM: number;
    layers: readonly Readonly<{
      name: string;
      thicknessM: number;
      /** `ifc://<file>#<expressID>` — the entity the thickness was read from. */
      ref: string;
    }>[];
    ref: string;
  }>[];
  /** How the orientation above was arrived at, including what was inferred. */
  orientation?: Readonly<{
    trueNorthDeg: number | null;
    /** True when the model states no true north and project north was used. */
    northAssumed: boolean;
    /** Walls sitting near the building's centre line, where outward is a weak call. */
    weakOutwardCount: number;
    wallCount: number;
    note: string;
  }>;
  site: Readonly<{
    declaredSiteName: string | null;
    declaredLatitudeDeg: number | null;
    declaredLongitudeDeg: number | null;
    locationIsAuthoringDefault: boolean;
    locationNote: string;
  }>;
  /**
   * Discipline models, each its own GLB so a layer nobody switches on is never
   * downloaded. Optional because a reference building need not have services.
   */
  serviceLayers?: readonly Readonly<{
    id: string;
    ko: string;
    en: string;
    file: string;
    byteLength: number;
    triangleCount: number;
    groups: readonly string[];
    /**
     * Every component is at its real geometry. What these describe is how it
     * is packed: a shape placed more than once is shipped once and instanced,
     * and `drawCalls` is what decides whether the layer is usable — an
     * instanced shape costs one draw call however often it is placed.
     *
     * Until 2026-09-04 these read `detailedRuns` / `proxiedComponents`,
     * because everything but runs and plant was a bounding box.
     */
    elements: number;
    distinctGeometries: number;
    instancedShapes: number;
    instancedPlacements: number;
    drawCalls: number;
    /**
     * Present only where the layer is NOT the model's own geometry — the
     * apartment's utility connections are drawn as boxes, and this sentence
     * is how the page says so under the row. Absent means the geometry is
     * the model's; it is never a decoration.
     */
    note?: string;
    /**
     * The routed network read out of the model's own distribution ports.
     *
     * `file` is null when the model states no direction of flow, and the
     * counts still say why — the Clinic's electrical model declares no ports
     * at all, which is a fact about what a coordination model carries rather
     * than a gap to fill in with a plausible circuit.
     */
    flow?: Readonly<{
      file: string | null;
      ports: number;
      connections: number;
      directedEdges: number;
      drawnEdges: number;
      /** Connections whose ports are SOURCEANDSINK — direction not stated. */
      bidirectionalEdges: number;
      unresolvedConnections: number;
      ungeometried: number;
      unreachedEdges: number;
      plantNodes: number;
      /** Segments downstream of plant, and the rest. */
      supplySegments: number;
      returnSegments: number;
      reason: string | null;
      /** Metres per animated pulse, so speed reads the same at any scale. */
      wavelengthM: number | null;
    }>;
  }>[];
  model: Readonly<{
    file: string;
    byteLength: number;
    triangleCount: number;
    groups: readonly string[];
    note: string;
    /**
     * How this building's service layers were packed, in the generator's
     * words and with the building's own figures. Emitted only when the
     * building has service layers; the page falls back to a generic sentence
     * that claims no number when it is absent.
     */
    serviceNote?: string;
  }>;
}>;

/**
 * One IfcSpace as `spaces.json` records it. Areas and the floor/volume
 * verdicts are the extractor's; nothing here is derived in the browser.
 */
export type ReferenceBuildingSpace = Readonly<{
  id: string;
  name: string;
  longName: string | null;
  storeyId: string | null;
  floorAreaSqm: number | null;
  areaQuantityName: string | null;
  countsAsFloorArea: boolean;
  countsAsConditionedVolume: boolean;
  excludedFromFloorAreaReason: string | null;
  netVolumeM3: number | null;
  netVolumeSource: "quantity" | "mesh" | null;
  grossVolumeM3: number | null;
  grossVolumeBasis: string | null;
  /** Plan bounding box in the fabric GLB's frame (Y up, metres). */
  extent: Readonly<{
    x: number;
    z: number;
    widthM: number;
    depthM: number;
    bottomM: number;
    topM: number;
  }> | null;
  ref: string;
}>;

export type ReferenceBuildingSpaces = Readonly<{
  kind: "bimfit_reference_building_spaces";
  id: string;
  spaces: readonly ReferenceBuildingSpace[];
}>;

/**
 * Catalog ids that have a published manifest.
 *
 * An id belongs here ONLY when `public/reference-buildings/<id>/manifest.json`
 * is committed. Adding one without the artifact turns an unrecognised route
 * into a recognised-but-404ing one, which is strictly worse: the same failure,
 * with the constant's documented meaning now false.
 */
export const REFERENCE_BUILDING_IDS = [
  "bs-medical-dental-clinic",
  "schependomlaan",
] as const;

export type ReferenceBuildingId = (typeof REFERENCE_BUILDING_IDS)[number];

export function isReferenceBuildingId(
  value: string,
): value is ReferenceBuildingId {
  return (REFERENCE_BUILDING_IDS as readonly string[]).includes(value);
}

export function referenceBuildingModelUrl(id: ReferenceBuildingId): string {
  return `/reference-buildings/${id}/model.glb`;
}

/** Directory holding a building's generated files. */
export function referenceBuildingBaseUrl(id: ReferenceBuildingId): string {
  return `/reference-buildings/${id}`;
}

/**
 * Read a manifest from `public/` on the server.
 *
 * `fs` rather than `fetch` so it works without an origin — the same reason
 * `StaticFileReleaseStore` reads its release manifests this way.
 */
export async function loadReferenceBuildingManifest(
  id: ReferenceBuildingId,
): Promise<ReferenceBuildingManifest | null> {
  const { readFile } = await import("node:fs/promises");
  const path = await import("node:path");
  try {
    const file = path.join(
      process.cwd(),
      "public",
      "reference-buildings",
      id,
      "manifest.json",
    );
    const parsed: unknown = JSON.parse(await readFile(file, "utf8"));
    if (
      typeof parsed !== "object" ||
      parsed === null ||
      (parsed as { kind?: unknown }).kind !== "bimfit_reference_building_manifest"
    ) {
      return null;
    }
    return parsed as ReferenceBuildingManifest;
  } catch {
    return null;
  }
}
