/**
 * The published face of a reference building.
 *
 * Generated by `scripts/build-reference-building.mjs` into
 * `public/reference-buildings/<id>/manifest.json` and read from there at
 * request time — never bundled. A card's figures and the model it opens must
 * come from the same file, or the two drift the first time extraction changes
 * and nothing notices.
 */
export type ReferenceBuildingManifest = Readonly<{
  kind: "bimfit_reference_building_manifest";
  schemaVersion: 1;
  id: string;
  name: Readonly<{ ko: string; en: string }>;
  summary: Readonly<{ ko: string; en: string }>;
  useType: string;
  licence: string;
  /** Rendered wherever the building is shown — a CC BY condition. */
  attribution: string;
  sourceUrl: string;
  generatedAt: string;
  sourceFiles: readonly Readonly<{
    role: string;
    fileName: string;
    sha256: string;
    byteLength: number;
  }>[];
  counts: Readonly<{
    storeys: number;
    spacesTotal: number;
    spacesFloor: number;
    assemblies: number;
    externalElements: number;
    exteriorWalls: number;
  }>;
  areas: Readonly<{
    /** Floor only. The denominator of every intensity figure. */
    totalFloorAreaSqm: number;
    /** The model's own area-plan total. Recorded, never divided by. */
    areaPlanTotalSqm: number;
    exteriorWallNetSqm: number;
    exteriorWallBelowRoofSqm: number;
    exteriorWallAboveRoofSqm: number;
    /**
     * Wall area per compass sector, summing to `exteriorWallNetSqm`.
     *
     * A monthly method needs this and a degree-day one does not: ISO 13790
     * computes solar gain per orientation, and the same 2,150.3 m² total
     * describes a very different building depending which way it faces.
     */
    exteriorWallByOrientationSqm?: Readonly<Record<string, number>>;
  }>;
  /** How the orientation above was arrived at, including what was inferred. */
  orientation?: Readonly<{
    trueNorthDeg: number | null;
    /** True when the model states no true north and project north was used. */
    northAssumed: boolean;
    /** Walls sitting near the building's centre line, where outward is a weak call. */
    weakOutwardCount: number;
    wallCount: number;
    note: string;
  }>;
  site: Readonly<{
    declaredSiteName: string | null;
    declaredLatitudeDeg: number | null;
    declaredLongitudeDeg: number | null;
    locationIsAuthoringDefault: boolean;
    locationNote: string;
  }>;
  /**
   * Discipline models, each its own GLB so a layer nobody switches on is never
   * downloaded. Optional because a reference building need not have services.
   */
  serviceLayers?: readonly Readonly<{
    id: string;
    ko: string;
    en: string;
    file: string;
    byteLength: number;
    triangleCount: number;
    groups: readonly string[];
    /**
     * Every component is at its real geometry. What these describe is how it
     * is packed: a shape placed more than once is shipped once and instanced,
     * and `drawCalls` is what decides whether the layer is usable — an
     * instanced shape costs one draw call however often it is placed.
     *
     * Until 2026-09-04 these read `detailedRuns` / `proxiedComponents`,
     * because everything but runs and plant was a bounding box.
     */
    elements: number;
    distinctGeometries: number;
    instancedShapes: number;
    instancedPlacements: number;
    drawCalls: number;
    /**
     * The routed network read out of the model's own distribution ports.
     *
     * `file` is null when the model states no direction of flow, and the
     * counts still say why — the Clinic's electrical model declares no ports
     * at all, which is a fact about what a coordination model carries rather
     * than a gap to fill in with a plausible circuit.
     */
    flow?: Readonly<{
      file: string | null;
      ports: number;
      connections: number;
      directedEdges: number;
      drawnEdges: number;
      /** Connections whose ports are SOURCEANDSINK — direction not stated. */
      bidirectionalEdges: number;
      unresolvedConnections: number;
      ungeometried: number;
      unreachedEdges: number;
      plantNodes: number;
      /** Segments downstream of plant, and the rest. */
      supplySegments: number;
      returnSegments: number;
      reason: string | null;
      /** Metres per animated pulse, so speed reads the same at any scale. */
      wavelengthM: number | null;
    }>;
  }>[];
  model: Readonly<{
    file: string;
    byteLength: number;
    triangleCount: number;
    groups: readonly string[];
    note: string;
  }>;
}>;

/** Catalog ids that have a published manifest. */
export const REFERENCE_BUILDING_IDS = ["bs-medical-dental-clinic"] as const;

export type ReferenceBuildingId = (typeof REFERENCE_BUILDING_IDS)[number];

export function isReferenceBuildingId(
  value: string,
): value is ReferenceBuildingId {
  return (REFERENCE_BUILDING_IDS as readonly string[]).includes(value);
}

export function referenceBuildingModelUrl(id: ReferenceBuildingId): string {
  return `/reference-buildings/${id}/model.glb`;
}

/** Directory holding a building's generated files. */
export function referenceBuildingBaseUrl(id: ReferenceBuildingId): string {
  return `/reference-buildings/${id}`;
}

/**
 * Read a manifest from `public/` on the server.
 *
 * `fs` rather than `fetch` so it works without an origin — the same reason
 * `StaticFileReleaseStore` reads its release manifests this way.
 */
export async function loadReferenceBuildingManifest(
  id: ReferenceBuildingId,
): Promise<ReferenceBuildingManifest | null> {
  const { readFile } = await import("node:fs/promises");
  const path = await import("node:path");
  try {
    const file = path.join(
      process.cwd(),
      "public",
      "reference-buildings",
      id,
      "manifest.json",
    );
    const parsed: unknown = JSON.parse(await readFile(file, "utf8"));
    if (
      typeof parsed !== "object" ||
      parsed === null ||
      (parsed as { kind?: unknown }).kind !== "bimfit_reference_building_manifest"
    ) {
      return null;
    }
    return parsed as ReferenceBuildingManifest;
  } catch {
    return null;
  }
}
