/**
 * Schependomlaan (Nijmegen) as energy-engine input — the Clinic's sibling.
 *
 * ══════════════════════════════════════════════════════════════════════════
 *  READ THIS BEFORE QUOTING ANY NUMBER FROM THIS FILE
 *
 *  This file is in the PLACEHOLDER state. `SCHEPENDOMLAAN_INPUT_STATE` says
 *  so at runtime, and `SCHEPENDOMLAAN_PENDING_MEASUREMENTS` lists, field by
 *  field, exactly which inputs are stand-ins, what they are stand-ins FOR,
 *  and which way each one biases the answer.
 *
 *  Three of this building's envelope inputs have never been measured: the
 *  glazing aperture (total and per orientation) and the exterior-door
 *  aperture, because `manifest.json` does not carry them yet. bim-bf's
 *  extractor pass (Lane B of the parity brief) will emit them under the
 *  manifest field names named in that table; swapping them in is a value
 *  change, not a rename, and flipping `SCHEPENDOMLAAN_INPUT_STATE` to
 *  "measured" is the last step.
 *
 *  Three more WERE placeholders until 2026-09-04 and are now measured: the
 *  roof (`areas.roofSurfaceByFamilySqm`, `roofUnionSqm`, `roofs[]`), the
 *  ground slab (`areas.groundSlabSqm`) and its exposed perimeter
 *  (`areas.groundPerimeterM`). Each moved the building the way its bias
 *  note predicted — the roof from 302.24 to 542.96 m², the slab from 302.24
 *  to 345.81 m², the perimeter from 69.54 to 90.08 m.
 *
 *  So: the wall areas, roof, ground, volumes, floor areas, storey datums
 *  and every layer thickness ARE measured and come from the committed
 *  manifest. The roof U, the wall U and the ground R_f are solved from the
 *  model's own stated layer sets. What is NOT measured is the glazed and
 *  door area, which sets the window term and the WWR denominator. A kWh/yr
 *  out of this file today is still provisional on that account.
 * ══════════════════════════════════════════════════════════════════════════
 *
 * Same discipline as `bs-medical-dental-clinic-energy.ts`, same four exports.
 * Every number here is either MEASURED (and says which extraction produced
 * it), PLACEHOLDER (and is in the pending table with the field it awaits), or
 * ASSUMED (and is in `SCHEPENDOMLAAN_ASSUMPTIONS` with the reason it cannot
 * be measured).
 *
 * Sources of the measurements:
 *   - `public/reference-buildings/schependomlaan/manifest.json`, generated by
 *     `scripts/build-reference-building.mjs` from the openBIMstandards
 *     Schependomlaan archive (CC BY 4.0).
 *   - `public/reference-buildings/schependomlaan/spaces.json`, 100 IfcSpace
 *     rows, for the room-name evidence behind the occupancy assumptions.
 *   - `docs/04_Agent-Handoffs/schependomlaan-parity-brief.md` (commit
 *     49e6900) for the decisions this lane was told not to re-open and for
 *     bim-bf's 17:19 identification of the cavity wall's three leaves.
 */

import type { BuildingRecipe, FloorSpec } from "@/lib/procedural/types";
import type { MaterialProperties } from "@/lib/material-types";
import { getRecipe } from "@/lib/procedural/recipe";
import { slabOnGroundUValue, slabOnGroundUValueRange } from "@/lib/energy-standards/ground-coupling";
import { calculateAssembly } from "@/lib/energy-standards/assembly";
import { genericMaterialById } from "@/lib/energy-standards/materials";

// ── Which state this file is in ───────────────────────────────────────────

/**
 * `"awaiting_lane_b_measurements"` while any row of
 * `SCHEPENDOMLAAN_PENDING_MEASUREMENTS` is still a placeholder. Exported so a
 * consumer — a page, a report, a test — can refuse to present these figures
 * as measurements, rather than relying on somebody having read a comment.
 */
export type SchependomlaanInputState = "awaiting_lane_b_measurements" | "measured";
export const SCHEPENDOMLAAN_INPUT_STATE: SchependomlaanInputState =
  "awaiting_lane_b_measurements";

export type PendingMeasurement = Readonly<{
  /** The `manifest.areas.*` field that will replace this value verbatim. */
  manifestField: string;
  /** The constant in this file that holds the stand-in. */
  constant: string;
  placeholderValue: number;
  unit: "m2" | "m";
  /** How the stand-in was arrived at. Never "typical for this building type". */
  derivedFrom: string;
  /** Which way it is wrong, in the building's favour or against it. */
  biasDirection: string;
}>;

// ── Measured geometry, from the committed manifest ────────────────────────

/**
 * Four occupied storeys at exactly 3.00 m floor-to-floor, datums 0 / 3 / 6 / 9.
 * `-1 fundering` (−1.00 m, 0 spaces) and `04 dak` (12.00 m, 0 spaces) are
 * datums, not storeys — `manifest.counts.storeys` is 4 while
 * `manifest.storeys` lists 6 rows, and the two do not disagree.
 */
const STOREY_F2F_M = 3.0;
const ROOF_DATUM_M = 12.0;

/** Per-storey floor area, `manifest.storeys[].floorAreaSqm`. */
export const SCHEPENDOMLAAN_STOREYS = Object.freeze({
  groundFloor: Object.freeze({ id: "storey-00-begane-grond", nameNl: "00 begane grond", elevationM: 0, floorToFloorM: STOREY_F2F_M, floorAreaSqm: 302.24, spaceCount: 32 }),
  firstFloor: Object.freeze({ id: "storey-01-eerste-verdieping", nameNl: "01 eerste verdieping", elevationM: 3, floorToFloorM: STOREY_F2F_M, floorAreaSqm: 290.56, spaceCount: 29 }),
  secondFloor: Object.freeze({ id: "storey-02-tweede-verdieping", nameNl: "02 tweede verdieping", elevationM: 6, floorToFloorM: STOREY_F2F_M, floorAreaSqm: 195.85, spaceCount: 20 }),
  thirdFloor: Object.freeze({ id: "storey-03-derde-verdieping", nameNl: "03 derde verdieping", elevationM: 9, floorToFloorM: STOREY_F2F_M, floorAreaSqm: 177.02, spaceCount: 19 }),
  /** Datum rows. Neither carries a space; neither is a storey. */
  foundationDatumM: -1.0,
  roofDatumM: ROOF_DATUM_M,
});

export const SCHEPENDOMLAAN_TOTAL_FLOOR_AREA_SQM = 965.67;

/** Exterior wall NET of openings — opaque inner leaf only, `areas.exteriorWallNetSqm`. */
const EXTERIOR_WALL_NET_SQM = 426.63;

/**
 * `areas.exteriorWallByOrientationSqm`, all eight sectors as the manifest
 * carries them. The four diagonals are 0 BY MEASUREMENT, not by omission:
 * `manifest.orientation.note` records that all 122 inner-leaf walls are
 * cardinal and that the 88 placements at 47.94° belong to the excluded outer
 * leaf. Lane B's per-sector glazing will arrive on these same eight keys.
 */
export type WallSector = "N" | "NE" | "E" | "SE" | "S" | "SW" | "W" | "NW";

export const SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM: Readonly<Record<WallSector, number>> =
  Object.freeze({
    N: 148.9,
    NE: 0,
    E: 104.67,
    SE: 0,
    S: 74.12,
    SW: 0,
    W: 98.94,
    NW: 0,
  });

const SECTORS = Object.keys(SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM) as readonly WallSector[];

// ── Placeholders. Every one of these is a stand-in, not a measurement ─────

/**
 * PLACEHOLDER for `areas.glazingApertureSqm`.
 *
 * The manifest states the COUNT — 77 windows — and no area at all. This is
 * that count times an assumed mean pane, which is a product of one measured
 * number and one invented one. See `A-GLAZING-AREA-PLACEHOLDER`.
 */
const WINDOW_COUNT = 77;
const PLACEHOLDER_MEAN_WINDOW_SQM = 1.5;
const PLACEHOLDER_GLAZING_APERTURE_SQM = WINDOW_COUNT * PLACEHOLDER_MEAN_WINDOW_SQM;

/**
 * PLACEHOLDER for `areas.exteriorDoorSqm`. 20 exterior door leaves, counted;
 * 2.0 m² each, invented. Kept a SEPARATE field from glazing from the start —
 * on the Clinic that separation is what stopped 267 m² of real wall going
 * un-priced, and folding doors into glazing here would repeat it.
 */
const EXTERIOR_DOOR_COUNT = 20;
const PLACEHOLDER_MEAN_DOOR_SQM = 2.0;
const PLACEHOLDER_EXTERIOR_DOOR_SQM = EXTERIOR_DOOR_COUNT * PLACEHOLDER_MEAN_DOOR_SQM;

// ── Ground and roof: measured 2026-09-04 ──────────────────────────────────

/**
 * `areas.groundSlabSqm`: the union of the 81 ground-storey slab shadows a
 * conditioned space stands on (`groundSlabs[]`, none excluded; stacked
 * build-up layers — vloer_V0, dekvloer, vloertegels — count once). It was a
 * 302.24 placeholder, the ground storey's floor area to the inside of the
 * walls, and the bias note said the real slab would be larger by roughly the
 * wall footprint. It is: 43.57 m² larger.
 */
const GROUND_SLAB_SQM = 345.81;

/**
 * `areas.groundPerimeterM`: the outline's outer ring. Two hole rings
 * totalling 4.06 m are not added — ISO 13370 wants the exposed perimeter,
 * and a hole in the slab outline is not exposed to outdoors. It was a 69.54
 * placeholder, the perimeter of a square of the placeholder area, and the
 * bias note said a square understates P. It did, by 30 %.
 */
const GROUND_PERIMETER_M = 90.08;

/**
 * The roof, from `areas.roofSurfaceByFamilySqm`, `roofProjectedByFamilySqm`,
 * `roofUnionSqm` and the 78 `roofs[]` rows. The families that are roofs:
 *
 *   sporenkap     surface 306.00   plan 124.90   the 57–65° pitched tiled roof
 *   dakvloer      surface 259.73   plan 135.37   9 flat decks on storey '04 dak'
 *   plat dak      surface  95.30   plan  95.01   6 flat decks, the low wing
 *   lifttop       surface   5.75   plan   5.75
 *   dak dakkapel  surface  14.49   plan  14.38   8 dormer roofs, flat
 *
 * and five thin families (plafond 3.33, dakisolatie 3.18, spouwisolatie
 * 2.42, dakaftimmering 1.84, dakelement 0) that are layers OF those roofs.
 * The engine's roof area is the OUTER SURFACE, and it is not the 692.04 the
 * family surfaces sum to — see A-ROOF-STACK for why a sum prices the same
 * roof twice — but:
 *
 *   sporenkap surface + (roofUnionSqm − sporenkap plan)
 *   = 306.00 + (361.86 − 124.90) = 306.00 + 236.96 = 542.96 m²
 *
 * The second term is the plan the flat roofs cover once — dakvloer 135.37 +
 * plat dak 95.01 + lifttop 5.75 = 236.13, plus 0.83 m² of dormer and trim
 * pieces reaching past those outlines — and a flat roof's surface is its
 * plan. Summing the four flat unions directly gives 542.42; the two differ
 * by that 0.83, well inside the rows' rounding.
 */
const ROOF_SPORENKAP_SURFACE_SQM = 306.0;
const ROOF_SPORENKAP_PLAN_SQM = 124.9;
/** `areas.roofUnionSqm`: the plan every roof family together covers, once. */
const ROOF_UNION_SQM = 361.86;
/** `areas.roofProjectedSqm`: the per-family unions summed (families overlap by 21.69). */
const ROOF_PROJECTED_SQM = 383.55;
const ROOF_FLAT_PLAN_SQM = ROOF_UNION_SQM - ROOF_SPORENKAP_PLAN_SQM;
export const SCHEPENDOMLAAN_ROOF_AREA_SQM = ROOF_SPORENKAP_SURFACE_SQM + ROOF_FLAT_PLAN_SQM;

/**
 * PLACEHOLDER for `areas.glazingByOrientationSqm`, on the same eight keys as
 * the wall split, so aperture ÷ wall gives a per-sector WWR the moment Lane B
 * lands. Distributed PRO RATA to the measured wall split, which is exactly
 * what "a uniform ratio across orientations" means — the diagonals stay 0
 * because their walls are 0. The real data is per-sector and will not be
 * uniform; see `A-WWR-UNIFORM-PLACEHOLDER`.
 */
const PLACEHOLDER_GLAZING_BY_SECTOR_SQM: Readonly<Record<WallSector, number>> =
  Object.freeze(
    Object.fromEntries(
      SECTORS.map((s) => [
        s,
        (SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM[s] / EXTERIOR_WALL_NET_SQM) *
          PLACEHOLDER_GLAZING_APERTURE_SQM,
      ]),
    ) as Record<WallSector, number>,
  );

/**
 * The whole placeholder set, machine-readable. A test asserts this list is
 * non-empty exactly while `SCHEPENDOMLAAN_INPUT_STATE` says it should be, so
 * the two cannot drift apart.
 */
export const SCHEPENDOMLAAN_PENDING_MEASUREMENTS: readonly PendingMeasurement[] =
  Object.freeze([
    {
      manifestField: "areas.glazingApertureSqm",
      constant: "PLACEHOLDER_GLAZING_APERTURE_SQM",
      placeholderValue: PLACEHOLDER_GLAZING_APERTURE_SQM,
      unit: "m2",
      derivedFrom:
        "77 windows counted by bim-bf × an invented 1.5 m² mean pane. The count is evidence; the mean is not.",
      biasDirection:
        "Unknown. A Dutch apartment mixes 3-4 m² living-room windows with 0.3-0.5 m² toilet lights, and 1.5 m² is a guess at the mean of that mixture.",
    },
    {
      manifestField: "areas.glazingByOrientationSqm",
      constant: "PLACEHOLDER_GLAZING_BY_SECTOR_SQM",
      placeholderValue: PLACEHOLDER_GLAZING_APERTURE_SQM,
      unit: "m2",
      derivedFrom:
        "The placeholder aperture distributed pro rata to the MEASURED wall split, giving one identical WWR on every sector.",
      biasDirection:
        "Understates the spread. A real Dutch block glazes its living-room facade far harder than its stair-and-service facade, so the true per-sector ratios straddle this one.",
    },
    {
      manifestField: "areas.exteriorDoorSqm",
      constant: "PLACEHOLDER_EXTERIOR_DOOR_SQM",
      placeholderValue: PLACEHOLDER_EXTERIOR_DOOR_SQM,
      unit: "m2",
      derivedFrom:
        "20 exterior door leaves counted by bim-bf × an invented 2.0 m² leaf.",
      biasDirection:
        "Roughly neutral on total loss — doors are priced at the wall U (A-DOORS) — but it moves the WWR denominator, so it is not free.",
    },
    // areas.roofProjectedSqm, areas.groundSlabSqm and areas.groundPerimeterM
    // left this table on 2026-09-04 when the extractor emitted them. All
    // three had said "Understates" here, and all three did.
  ]);

// ── The envelope this file hands the engine ───────────────────────────────

/**
 * `provenance` is the point of this object: every field says whether it is a
 * manifest measurement, a placeholder awaiting Lane B, or derived from the
 * two. The Clinic has no equivalent because the Clinic has no placeholders.
 */
export const SCHEPENDOMLAAN_MEASURED_ENVELOPE = Object.freeze({
  exteriorWallNetSqm: EXTERIOR_WALL_NET_SQM,
  exteriorWallByOrientationSqm: SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM,
  exteriorWallBelowRoofSqm: 411.76,
  exteriorWallAboveRoofSqm: 14.87,
  northAssumed: true,
  glazingApertureSqm: PLACEHOLDER_GLAZING_APERTURE_SQM,
  glazingByOrientationSqm: PLACEHOLDER_GLAZING_BY_SECTOR_SQM,
  exteriorDoorSqm: PLACEHOLDER_EXTERIOR_DOOR_SQM,
  /** Opaque wall + glazing + doors: the whole exterior wall plane. */
  grossWallSqm:
    EXTERIOR_WALL_NET_SQM +
    PLACEHOLDER_GLAZING_APERTURE_SQM +
    PLACEHOLDER_EXTERIOR_DOOR_SQM,
  /** `areas.roofProjectedSqm` — per-family plan unions summed. Recorded, not the engine's. */
  roofProjectedSqm: ROOF_PROJECTED_SQM,
  /** `areas.roofUnionSqm` — the plan all roof families cover, once. */
  roofUnionSqm: ROOF_UNION_SQM,
  /** The pitched roof's one-sheet surface and its plan, `roofSurfaceByFamilySqm.sporenkap` / `roofProjectedByFamilySqm.sporenkap`. */
  roofSporenkapSurfaceSqm: ROOF_SPORENKAP_SURFACE_SQM,
  roofSporenkapPlanSqm: ROOF_SPORENKAP_PLAN_SQM,
  /** The outer surface the engine prices: 306.00 + (361.86 − 124.90). See A-ROOF-STACK. */
  roofAreaSqm: SCHEPENDOMLAAN_ROOF_AREA_SQM,
  groundSlabSqm: GROUND_SLAB_SQM,
  groundPerimeterM: GROUND_PERIMETER_M,
  /** `areas.conditionedVolumeGrossM3` — inside the air barrier. Measured. */
  conditionedVolumeGrossM3: 2897.04,
  /** `areas.roomVolumeNetM3` — the 100 space solids summed. Recorded, not used. */
  roomVolumeNetM3: 2530.05,
  provenance: Object.freeze({
    exteriorWallNetSqm: "manifest",
    exteriorWallByOrientationSqm: "manifest",
    exteriorWallBelowRoofSqm: "manifest",
    exteriorWallAboveRoofSqm: "manifest",
    glazingApertureSqm: "placeholder",
    glazingByOrientationSqm: "placeholder",
    exteriorDoorSqm: "placeholder",
    grossWallSqm: "derived_from_placeholder",
    roofProjectedSqm: "manifest",
    roofUnionSqm: "manifest",
    roofSporenkapSurfaceSqm: "manifest",
    roofSporenkapPlanSqm: "manifest",
    roofAreaSqm: "derived_from_manifest",
    groundSlabSqm: "manifest",
    groundPerimeterM: "manifest",
    conditionedVolumeGrossM3: "manifest",
    roomVolumeNetM3: "manifest",
  }),
});

// ── Constructions, solved from the model's own layer sets ─────────────────

const lambda = (id: string): number => {
  const material = genericMaterialById(id);
  const value = material?.conductivityWPerMK;
  if (value === undefined) {
    throw new Error(`generic material ${id} states no conductivity`);
  }
  return value;
};

const fixedR = (id: string): number => {
  const material = genericMaterialById(id);
  const value = material?.fixedResistanceM2KPerW;
  if (value === undefined) {
    throw new Error(`generic material ${id} states no fixed resistance`);
  }
  return value;
};

/**
 * The exterior wall is a CAVITY WALL whose three leaves are three separate
 * `IfcMaterialLayerSet`s. The file never states them as one assembly; that
 * composite is this file's inference, and it is built here rather than in
 * `constructions.ts` for exactly that reason — `constructions.ts` solves
 * assemblies the model states, and this is not one of them.
 *
 * Identified by bim-bf at 17:19 (parity brief, "Decisions already taken"):
 *   inner leaf  `IFC_kalkzandsteen_100mm`      100 mm calcium-silicate
 *   cavity      `IFC_isolatie_110mm_glaswol`   110 mm glass wool
 *   outer leaf  `IFC_baksteen_*_100mm`         100 mm clay facing brick
 *
 * No air gap between insulation and outer leaf is included: Dutch cavity
 * walls normally have one and this model does not state one, so none is
 * added. Including a 30 mm gap would take U from 0.289 to about 0.275.
 */
export const SCHEPENDOMLAAN_CAVITY_WALL = calculateAssembly(
  [
    { id: "IFC_baksteen_roodbruin_100mm (outer leaf)", thicknessM: 0.1, conductivityWPerMK: lambda("st-redbrick") },
    { id: "IFC_isolatie_110mm_glaswol (cavity)", thicknessM: 0.11, conductivityWPerMK: lambda("ins-gw") },
    { id: "IFC_kalkzandsteen_100mm (inner leaf)", thicknessM: 0.1, conductivityWPerMK: lambda("st-brick") },
  ],
  "horizontal",
);

/** The same wall with the 120 mm inner leaf the model also carries: U 0.2868. */
export const SCHEPENDOMLAAN_CAVITY_WALL_120MM_LEAF = calculateAssembly(
  [
    { id: "IFC_baksteen_roodbruin_100mm (outer leaf)", thicknessM: 0.1, conductivityWPerMK: lambda("st-redbrick") },
    { id: "IFC_isolatie_110mm_glaswol (cavity)", thicknessM: 0.11, conductivityWPerMK: lambda("ins-gw") },
    { id: "IFC_kalkzandsteen_120mm (inner leaf)", thicknessM: 0.12, conductivityWPerMK: lambda("st-brick") },
  ],
  "horizontal",
);

/**
 * `IFC_dakplaat_geisoleerd_Rc=4,00`, solved from its three stated layers with
 * UPWARD surface resistances. Direction is not cosmetic: taking the
 * horizontal row instead gives 0.1768, which reads better than the roof is.
 *
 * The name states Rc 4.00 and the layers solve to Rc 5.50 — a 37.6 %
 * disagreement, well past the brief's 10 % threshold. This file uses the
 * SOLVED value and says why in `A-ROOF-RC-CONFLICT`; it is the optimistic of
 * the two and the reader is told so there.
 */
export const SCHEPENDOMLAAN_ROOF = calculateAssembly(
  [
    { id: "99 Lucht frame", thicknessM: 0.005, fixedResistanceM2KPerW: fixedR("air-10") },
    { id: "99 Isolatie - Glaswol 190mm", thicknessM: 0.19, conductivityWPerMK: lambda("ins-gw") },
    { id: "01 plaatmateriaal - spaanplaat - wit", thicknessM: 0.011, conductivityWPerMK: lambda("wd-plywood") },
  ],
  "upward",
);

/** The Rc the assembly's own name states, and the roof U it implies. */
export const SCHEPENDOMLAAN_ROOF_STATED_RC = 4.0;
export const SCHEPENDOMLAAN_ROOF_STATED_RC_U =
  1 / (SCHEPENDOMLAAN_ROOF_STATED_RC + 0.086 + 0.043);

/**
 * `IFC_vloer_geisoleerde_kanaalplaat_Rc=3,00` — the floor construction's own
 * resistance R_f, layers only, EXCLUDING surface resistances, which is
 * exactly what ISO 13370 wants. 200 mm precast concrete + 133 mm EPS.
 *
 * NOT `calculateAssembly`'s U. A slab on grade faces soil, not outdoor air;
 * `ground-coupling.ts` opens with what that error costs.
 */
const GROUND_FLOOR_RESISTANCE_M2KW =
  0.2 / lambda("st-rc") + 0.133 / lambda("ins-eps1");

/** The Rc the assembly's own name states. Solved 3.78 against a stated 3.00. */
export const SCHEPENDOMLAAN_GROUND_STATED_RC = 3.0;

/** Cavity-wall total thickness at the slab edge: 100 + 110 + 100 mm. */
const WALL_THICKNESS_AT_SLAB_M = 0.31;

const groundInputs = {
  areaSqm: GROUND_SLAB_SQM,
  exposedPerimeterM: GROUND_PERIMETER_M,
  wallThicknessM: WALL_THICKNESS_AT_SLAB_M,
  floorResistanceM2KPerW: GROUND_FLOOR_RESISTANCE_M2KW,
} as const;

/**
 * 345.81 m² over 90.08 m: B' = 7.68 m, d_t = 8.29 m, U = 0.1695 W/m²K. On
 * the placeholder square (302.24 / 69.54) it read 0.1637 with B' 8.69 — and
 * the regime flipped exactly as that file predicted: d_t now exceeds B', so
 * this is ISO 13370's `well-insulated` branch. The measured perimeter made
 * the floor 3.5 % lossier, which is the direction the bias note gave.
 */
export const SCHEPENDOMLAAN_GROUND_FLOOR = slabOnGroundUValue(groundInputs);
export const SCHEPENDOMLAAN_GROUND_FLOOR_RANGE = slabOnGroundUValueRange(groundInputs);

/** The same slab read at the stated Rc 3.00 instead of the solved 3.78. */
export const SCHEPENDOMLAAN_GROUND_FLOOR_AT_STATED_RC = slabOnGroundUValue({
  ...groundInputs,
  floorResistanceM2KPerW: SCHEPENDOMLAAN_GROUND_STATED_RC,
});

// ── Window-to-wall ratio: derived from its parts, against GROSS wall ──────

/**
 * The engine computes `windows = grossWall × wwr` and prices `grossWall −
 * windows` as opaque wall, so the ratio must be quoted against the same gross
 * the engine is handed — opaque + glazing + doors. Quoting it against the net
 * 426.63 would silently un-price the 40 m² of doors and 115.5 m² of glazing.
 *
 * Derived from the parts, never typed. Today the parts include two
 * placeholders, so the RATIO is provisional even though the ARITHMETIC is not:
 * when Lane B's numbers land, this expression is unchanged and the value moves.
 */
const WWR_AGAINST_GROSS_WALL =
  SCHEPENDOMLAAN_MEASURED_ENVELOPE.glazingApertureSqm /
  SCHEPENDOMLAAN_MEASURED_ENVELOPE.grossWallSqm;

/**
 * Per-sector WWR against each sector's own gross wall, on all eight keys.
 *
 * This is the shape Lane B's `glazingByOrientationSqm` plugs into, and it is
 * what the 방위별 창면적비 legend wants. It is deliberately NOT what is handed
 * to `MaterialProperties.windowToWallRatio`: `heat-loss.ts:109` takes the
 * UNWEIGHTED mean of the four cardinal ratios and multiplies the whole gross
 * wall by it, so feeding four genuinely different per-sector ratios in there
 * would not reproduce the total aperture — a 148.90 m² north wall and a 74.12
 * m² south wall would get equal weight. See `A-WWR-ENGINE-MEAN`.
 */
export const SCHEPENDOMLAAN_WWR_BY_SECTOR: Readonly<Record<WallSector, number>> =
  Object.freeze(
    Object.fromEntries(
      SECTORS.map((s) => {
        const wall = SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM[s];
        const glazing = PLACEHOLDER_GLAZING_BY_SECTOR_SQM[s];
        const doors =
          (wall / EXTERIOR_WALL_NET_SQM) * PLACEHOLDER_EXTERIOR_DOOR_SQM;
        const gross = wall + glazing + doors;
        return [s, gross > 0 ? glazing / gross : 0];
      }),
    ) as Record<WallSector, number>,
  );

// ── The recipe: shape and metadata only ───────────────────────────────────

const floors: FloorSpec[] = [
  { floorNo: 1, label: "1F — 00 begane grond", type: "above", y: 0, height: STOREY_F2F_M, isGroundFloor: true, useCode: "02000" },
  { floorNo: 2, label: "2F — 01 eerste verdieping", type: "above", y: 3, height: STOREY_F2F_M, isGroundFloor: false, useCode: "02000" },
  { floorNo: 3, label: "3F — 02 tweede verdieping", type: "above", y: 6, height: STOREY_F2F_M, isGroundFloor: false, useCode: "02000" },
  { floorNo: 4, label: "4F — 03 derde verdieping", type: "above", y: 9, height: STOREY_F2F_M, isGroundFloor: false, useCode: "02000" },
];

/**
 * The footprint the recipe carries is a SQUARE of the ground storey's floor
 * area. It is not a measurement and nothing in the energy path reads it:
 * `measuredEnvelope` below short-circuits `envelopeQuantities`, which is why
 * a shape-free stand-in is admissible here at all. See `A-NO-FOOTPRINT`.
 */
const FOOTPRINT_SIDE_M =
  Math.round(Math.sqrt(SCHEPENDOMLAAN_STOREYS.groundFloor.floorAreaSqm) * 100) / 100;

/**
 * Era 2010-2019: the archive's coordination models are dated 2015-09-23 and
 * the project was built 2015-16. What the era does here is select Korean
 * code-table defaults for anything not overridden — and every thermal value
 * that matters IS overridden below, so the era's only surviving effect is on
 * cosmetic recipe fields. It does NOT decide a single U-value, WWR or
 * airtightness figure in this file.
 */
const defaults = getRecipe("22", "2010-2019", "02000", false);

export const SCHEPENDOMLAAN_RECIPE: BuildingRecipe = {
  ...defaults,
  era: "2010-2019",
  buildingName: "Schependomlaan Apartments",
  address:
    "Nijmegen, Netherlands (town stated on IfcSite and IfcBuilding). The IfcSite coordinate is a stamped Amersfoort constant 46.2 km away and is not used.",
  footprintWidth: FOOTPRINT_SIDE_M,
  footprintDepth: FOOTPRINT_SIDE_M,
  officialFloorAreaSqm: SCHEPENDOMLAAN_TOTAL_FLOOR_AREA_SQM,
  floors,
  totalHeight: ROOF_DATUM_M,
  wallThickness: WALL_THICKNESS_AT_SLAB_M,
  mainPurpsCd: "02000",
  strctCd: "22",
  siteWidth: FOOTPRINT_SIDE_M,
  siteDepth: FOOTPRINT_SIDE_M,
  measuredEnvelope: {
    planAreaSqm: SCHEPENDOMLAAN_MEASURED_ENVELOPE.groundSlabSqm,
    wallLengthM: SCHEPENDOMLAAN_MEASURED_ENVELOPE.groundPerimeterM,
    grossWallAreaSqm: SCHEPENDOMLAAN_MEASURED_ENVELOPE.grossWallSqm,
    roofAreaSqm: SCHEPENDOMLAAN_MEASURED_ENVELOPE.roofAreaSqm,
    volumeM3: SCHEPENDOMLAAN_MEASURED_ENVELOPE.conditionedVolumeGrossM3,
    derivedFloorAreaSqm: SCHEPENDOMLAAN_TOTAL_FLOOR_AREA_SQM,
    basis:
      "PARTLY PLACEHOLDER — see SCHEPENDOMLAAN_PENDING_MEASUREMENTS. Wall areas, " +
      "floor areas, volumes, roof and ground are read from the Schependomlaan IFC " +
      "by scripts/build-reference-building.mjs (inner-leaf exterior-wall walk, " +
      "IfcSpace rows, storey datums, per-element roof shadows and one-sheet " +
      "surfaces, the union of the ground-storey slab shadows and its outer ring). " +
      "The roof area is the outer surface, derived as sporenkap surface 306.00 + " +
      "(roofUnionSqm 361.86 − sporenkap plan 124.90) = 542.96 m² (A-ROOF-STACK). " +
      "Glazing aperture and exterior-door aperture are NOT measured: they are " +
      "stand-ins awaiting bim-bf's extractor pass and each biases the answer in " +
      "the direction that table records.",
  },
};

// ── Materials ─────────────────────────────────────────────────────────────

const wallLayers = [
  { name: "03 mw-baksteen (outer leaf, clay facing brick)", thickness: 0.1, thermalConductivity: lambda("st-redbrick"), density: 1700, specificHeat: 880 },
  { name: "99 Isolatie - Glaswol (cavity)", thickness: 0.11, thermalConductivity: lambda("ins-gw"), density: 24, specificHeat: 840 },
  { name: "03 Metselwerk - kalkzandsteen C (inner leaf)", thickness: 0.1, thermalConductivity: lambda("st-brick"), density: 1800, specificHeat: 880 },
];

const wall = (orientation: "N" | "S" | "E" | "W", surfaceArea: number) => ({
  orientation,
  uValue: SCHEPENDOMLAAN_CAVITY_WALL.uValueWPerM2K,
  rValue: SCHEPENDOMLAAN_CAVITY_WALL.totalResistanceM2KPerW,
  layers: wallLayers,
  thermalBridge: 0,
  surfaceArea,
});

export const SCHEPENDOMLAAN_MATERIALS: MaterialProperties = {
  source: "ifc-model",
  confidence: "estimated",
  codeYear: 2015,
  envelope: {
    walls: [
      wall("N", SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM.N),
      wall("E", SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM.E),
      wall("S", SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM.S),
      wall("W", SCHEPENDOMLAAN_WALL_BY_SECTOR_SQM.W),
    ],
    /**
     * One roof U for a roof the rows now show is two kinds — 306.00 m² of
     * 64° tiled sporenkap and 236.96 m² of flat deck (dakvloer, plat dak,
     * lifttop). The model states one insulated roof assembly,
     * IFC_dakplaat_geisoleerd, and no separate flat-deck build-up that
     * constructions.ts resolves, so there is nothing measured to weight
     * against and the single solved U is applied to the whole outer surface.
     * See A-ROOF-STACK.
     */
    roof: {
      uValue: SCHEPENDOMLAAN_ROOF.uValueWPerM2K,
      layers: [
        { name: "99 Lucht frame", thickness: 0.005, thermalConductivity: 0.036, density: 1.2, specificHeat: 1005 },
        { name: "99 Isolatie - Glaswol 190mm", thickness: 0.19, thermalConductivity: lambda("ins-gw"), density: 24, specificHeat: 840 },
        { name: "01 plaatmateriaal - spaanplaat - wit", thickness: 0.011, thermalConductivity: lambda("wd-plywood"), density: 500, specificHeat: 1600 },
      ],
      /** Clay roof tiles, `WILLEMSEN-*dakpannen` in the archive. */
      solarReflectance: 0.3,
      emissivity: 0.9,
      greenRoofCoverage: 0,
    },
    groundFloor: {
      uValue: SCHEPENDOMLAAN_GROUND_FLOOR.uValueWPerM2K,
      layers: [
        { name: "02 Beton gewapend - prefab VLOER (kanaalplaat)", thickness: 0.2, thermalConductivity: lambda("st-rc"), density: 2400, specificHeat: 880 },
        { name: "99 Isolatie - EPS", thickness: 0.133, thermalConductivity: lambda("ins-eps1"), density: 15, specificHeat: 1450 },
      ],
      /** ISO 13370's soil path is already inside the U above; nothing to add. */
      groundContactResistance: 0,
    },
    windows: {
      uValue: 1.6,
      shgc: 0.6,
      vlt: 0.75,
      glassType: "double",
      coating: "low-e",
      gasFill: "argon",
      frameMaterial: "wood",
      airLeakageRate: 0.3,
      shadingCoefficient: 0.69,
      windowToWallRatio: {
        N: WWR_AGAINST_GROSS_WALL,
        S: WWR_AGAINST_GROSS_WALL,
        E: WWR_AGAINST_GROSS_WALL,
        W: WWR_AGAINST_GROSS_WALL,
      },
    },
    foundation: {
      perimeterInsulationUValue: 0,
      groundTemperature: 13.5,
      moistureBarrier: "none",
    },
    airtightness: {
      ach50: 2.05,
      equivalentLeakageArea: 0,
      testMethod: "estimated",
    },
  },
  hvac: {
    heating: { systemType: "individual", fuelType: "gas", efficiency: 0.9, capacity: 0 },
    /** 0 is how `annual-demand.ts:78` is told a building has no cooling. */
    cooling: { systemType: "none", efficiency: 0, capacity: 0 },
    ventilation: { type: "mechanical-exhaust", heatRecoveryEfficiency: 0, airflowRate: 0 },
    dhw: { systemType: "gas-boiler", efficiency: 0.85, storageVolume: 0 },
  },
  lighting: {
    // The repo's own 공동주택 row (korean-building-codes.ts:176), rather
    // than a figure invented here. See A-LPD.
    lightingPowerDensity: 6,
    controlType: "manual",
    lampType: "led",
  },
  renewable: {
    solarPV: { installed: false, capacity: 0, panelType: "monocrystalline", tiltAngle: 0, orientation: 0, area: 0 },
    solarThermal: { installed: false, collectorArea: 0, efficiency: 0 },
    geothermal: { installed: false, systemType: "closed-loop", cop: 0 },
  },
  occupancy: {
    occupancyDensity: 0.025,
    weekdaySchedule: [1, 1, 1, 1, 1, 1, 0.9, 0.7, 0.4, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.6, 0.8, 0.9, 1, 1, 1, 1, 1],
    weekendSchedule: [1, 1, 1, 1, 1, 1, 1, 0.9, 0.8, 0.7, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.7, 0.8, 0.9, 1, 1, 1, 1, 1],
    // Both are the repo's own 공동주택 row (korean-building-codes.ts:186),
    // NOT figures derived here: neither is read anywhere in `src/lib/energy`,
    // and `hotWaterDemand` has no unit in `material-types.ts` at all. See
    // A-OCCUPANCY.
    internalHeatGain: 3,
    hotWaterDemand: 40,
  },
};

// ── Every assumption, named ───────────────────────────────────────────────

export type SchependomlaanAssumption = Readonly<{ id: string; assumes: string; why: string }>;

export const SCHEPENDOMLAAN_ASSUMPTIONS: readonly SchependomlaanAssumption[] =
  Object.freeze([
    // ── The placeholder state itself ──────────────────────────────────────
    { id: "A-PLACEHOLDER-STATE", assumes: "Three envelope inputs are stand-ins, not measurements: glazing aperture, per-orientation glazing and exterior-door aperture.", why: "The committed manifest carries none of them — it states window and door COUNTS (77 / 20) and no apertures. bim-bf's extractor pass emits them as areas.glazingApertureSqm, areas.glazingByOrientationSqm and areas.exteriorDoorSqm; SCHEPENDOMLAAN_PENDING_MEASUREMENTS names each stand-in, how it was derived and which way it is wrong. SCHEPENDOMLAAN_INPUT_STATE reads 'awaiting_lane_b_measurements' until every one of them is replaced. Three more — roof, ground-slab area and ground perimeter — were stand-ins until 2026-09-04 and are measured now; each had said 'Understates' and each did (roof 302.24 → 542.96 m², slab 302.24 → 345.81 m², perimeter 69.54 → 90.08 m). A kWh figure from this file today is provisional on its window term in a way its U-values are not." },
    { id: "A-GLAZING-AREA-PLACEHOLDER", assumes: "77 windows at a mean 1.5 m² give a 115.50 m² aperture.", why: "The count is bim-bf's measurement; the mean pane is invented. A Dutch apartment mixes 3-4 m² living-room windows with 0.3-0.5 m² toilet lights and the mean of that mixture is not knowable from a count. The resulting 19.8 % WWR against gross wall is plausible for Dutch housing, which is exactly why it must be labelled — a plausible number is indistinguishable from a measured one once it has been multiplied by a U-value." },
    { id: "A-DOORS-AREA-PLACEHOLDER", assumes: "20 exterior door leaves at a mean 2.0 m² give 40.00 m².", why: "Same shape as the glazing placeholder: the count is measured, the leaf area is not. Doors are kept a separate field from glazing rather than folded in, because on the Clinic that separation is what stopped 267 m² of real wall being priced as nothing, and the gross-wall denominator is wrong the moment they merge." },
    { id: "A-ROOF-STACK", assumes: "The roof the engine prices is the outer surface, 542.96 m² = sporenkap surface 306.00 + (roofUnionSqm 361.86 − sporenkap plan 124.90), not the 692.04 m² the ten family surfaces sum to and not the 383.55 m² roofProjectedSqm.", why: "The family surfaces cannot simply be summed, because they overlap in plan and are layers of the same roofs: dakvloer's nine slabs on storey '04 dak' (11.62–11.84 m) surface 259.73 but union to 135.37 — eight build-up slabs stacked on one deck, which a sum prices twice; the eight dormer roofs (14.49) and the thin plafond / dakisolatie / spouwisolatie / dakaftimmering pieces (10.77) sit inside the sporenkap's plan on top of it. What the rows do NOT show is the dakvloer under the sporenkap — the 64° sporenkap (44 ROOF slabs, 32 of them on storey 03 at 9.00 m, under the dakvloer's 11.62–11.84 m) is a steep band about 1.3 m wide around the top storey, and the flat dakvloer, plat dak and lifttop lie beside it: their unions 135.37 + 95.01 + 5.75 = 236.13 against the all-family union's 361.86 − 124.90 = 236.96, disjoint from the pitched roof to within 0.83 m². So the outer surface is the pitched roof at its surface plus the flat roofs at their plan, which is their surface. The dormer roofs are left inside the sporenkap's figure rather than added — if the sporenkap is cut at the dormers this understates by up to 14.49 m² plus the dormer cheeks. One solved roof U (the dakplaat panel) is applied to all of it, because the model resolves no separate flat-deck build-up; the flat decks may be built differently and the file does not say." },
    { id: "A-WWR-UNIFORM-PLACEHOLDER", assumes: "The placeholder glazing is spread pro rata to the measured wall split, so every sector reads the same WWR.", why: "Lane B emits glazingByOrientationSqm on the same eight sector keys as the wall split, so a genuine per-sector WWR is coming and this file is structured to take one — SCHEPENDOMLAAN_WWR_BY_SECTOR already computes eight ratios. Until then a uniform spread is the only distribution that adds no information the file does not have. It is not what the building looks like: a Dutch block glazes its living-room facade far harder than its stair-and-service facade." },

    // ── The engine's own limits, disclosed ────────────────────────────────
    { id: "A-WWR-DENOMINATOR", assumes: "WWR 0.1984 against GROSS wall area (opaque 426.63 + glazing 115.50 + doors 40.00 = 582.13 m²).", why: "heat-loss.ts computes windows = gross × WWR and prices the remainder as opaque wall, so the ratio must be quoted against the same gross the engine is handed. Against the net 426.63 the windows would land right and 155 m² of real wall would be priced as nothing. Derived from the parts in code, never typed — so when the placeholders are replaced the expression is unchanged and the ratio simply moves." },
    { id: "A-WWR-ENGINE-MEAN", assumes: "All four cardinal ratios handed to MaterialProperties are the single whole-building ratio.", why: "heat-loss.ts:109 takes the UNWEIGHTED arithmetic mean of the four cardinals and multiplies the whole gross wall by it. Handing it four genuinely different per-sector ratios would give a 148.90 m² north wall and a 74.12 m² south wall equal weight and would not reproduce the total aperture. The per-sector figures live in SCHEPENDOMLAAN_WWR_BY_SECTOR for the legend; wiring them into the engine needs an area-weighted mean in heat-loss.ts, which is not this lane's file." },
    { id: "A-DOORS", assumes: "The 40.00 m² of exterior door leaves are priced at the wall U-value.", why: "The engine knows walls and windows and nothing between. A Dutch apartment entrance door is an insulated opaque leaf, so the wall U is the nearer of the two; leaving the doors out entirely would make the modelled envelope smaller than the building." },
    { id: "A-GROUND-DT", assumes: "The engine's 13.5 °C ground temperature and 4,380 h ground season.", why: "ISO 13370's U pairs with the annual-mean external air temperature, and the engine applies a fixed 6.5 K drop instead. The mismatch is about 13 % conservative — in the direction that makes the building look worse. It is disclosed rather than reconciled here, because reconciling it moves every other building in the app." },

    // ── Constructions ────────────────────────────────────────────────────
    { id: "A-CAVITY-WALL", assumes: "The exterior wall is one 310 mm cavity assembly at U 0.2889 W/m²K (Rc 3.309), built from three separate layer sets: IFC_baksteen_*_100mm outer, IFC_isolatie_110mm_glaswol cavity, IFC_kalkzandsteen_100mm inner.", why: "The file never states these as one assembly — the leaves are separate IfcWall instances and separate IfcMaterialLayerSets, and combining them is this file's inference, not the model's statement. It is built here rather than in constructions.ts for that reason. The value sits inside the 0.28-0.33 the parity brief expected, and the Dutch 2012 Bouwbesluit minimum for walls was Rc 3.5, so as modelled this wall is marginally short of the code it was built under. The model also carries a 120 mm inner leaf (U 0.2868, 0.7 % different); the 100 mm is used and the other is exported beside it." },
    { id: "A-CAVITY-AIR-GAP", assumes: "No ventilated or unventilated air gap between the insulation and the outer leaf.", why: "Dutch cavity walls normally have one and this model states none, so none is added — a stated layer set is the source, not a mental picture of how the wall was probably built. Adding a 30 mm gap would take the wall from U 0.289 to about 0.275, so the omission costs the building about 5 %, in the direction that makes it look worse." },
    { id: "A-KALKZANDSTEEN-LAMBDA", assumes: "Calcium-silicate blockwork at λ 0.8 W/m·K, the library's concrete-brick entry.", why: "GENERIC_MATERIALS has no calcium-silicate row and adding one belongs to the standards library's own traceability ledger, not to a reference building. Real kalkzandsteen is nearer λ 1.0, which would cut the inner leaf's R from 0.125 to 0.100 — 0.7 % of the wall assembly. Named rather than searched: searchGenericMaterials substring-matches Korean and English names and would return nothing for any Dutch layer name in this model." },
    { id: "A-ROOF-RC-CONFLICT", assumes: "The roof U is the SOLVED 0.1776 W/m²K (Rc 5.502), not the 0.2422 its name's stated Rc 4.00 implies.", why: "A 37.6 % disagreement, well past the brief's 10 % threshold. The solved value is used because this module's whole claim is layers → U, the honest direction, and because 'Rc=4,00' is a token in an assembly NAME, not an IfcThermalTransmittance the file declares: 190 mm of glass wool genuinely is about Rc 5.3-5.5, and the name almost certainly records the specification the assembly was created to satisfy rather than what it achieves. The reader is owed the direction: the solved figure is the OPTIMISTIC of the two, and A-ROOF-FRAME-BRIDGE names the effect that closes part of the gap." },
    { id: "A-ROOF-FRAME-BRIDGE", assumes: "No thermal bridging through the roof panel's frame.", why: "The assembly's own first layer is named '99 Lucht frame' — the model says there is a frame in it. A framed cavity breaks ISO 6946 5.3.1's unsubdivided-layer premise outright, and the timber ribs of a dakplaat typically cost 10-20 % of the assembly's resistance. That bridge is unrepresented and is disclosed rather than tuned away, and it pushes the roof from the solved Rc 5.50 back toward the stated 4.00." },
    { id: "A-ROOF-AIR-LAYER", assumes: "The 5 mm '99 Lucht frame' layer contributes R 0.14, the library's 10 mm cavity entry.", why: "Three things are wrong with that and all three are disclosed rather than tuned. (1) The void is SUBDIVIDED — the name says 'frame' — so ISO 6946 Table 2's unsubdivided-layer premise (5.3.1) does not hold and the bridge through the ribs is unrepresented. (2) 5 mm is below every row available: Table 2's flat 0.16/0.18 values start at 25 mm and the library's smallest cavity is 10 mm, so the nearest entry over-states this layer by roughly 0.03 m²K/W, 0.5 % of the roof's resistance. (3) The layer is upward-facing in the roof and downward-facing in IFC_verlaagd_plafond, and a name-keyed mapping table cannot carry two heat-flow directions for one name." },
    { id: "A-GROUND-RC-CONFLICT", assumes: "The floor construction resistance R_f is the SOLVED 3.781 m²K/W, not the stated Rc 3.00.", why: "A 26 % disagreement, again past the 10 % threshold, and again the solved figure is the optimistic one: at the stated Rc the ground U would be 0.1974 instead of 0.1695, 16 % worse. The solved value is used for consistency with the roof and with the Clinic. Both are exported — SCHEPENDOMLAAN_GROUND_FLOOR_AT_STATED_RC carries the other reading — because the difference is larger than the soil uncertainty this building's ground U already carries." },
    { id: "A-HOLLOW-CORE", assumes: "The 200 mm kanaalplaat is solid reinforced concrete at λ 2.3.", why: "A kanaalplaat is a hollow-core slab: its voids give it more resistance than the solid concrete modelled here, so this understates the floor. The library has no hollow-core entry and inventing an effective λ for one would be a manufacturer's figure dressed as a generic table value. The error is small against 133 mm of EPS — the concrete is 2.3 % of the stack's resistance either way." },
    { id: "A-SUSPENDED-FLOOR", assumes: "The ground floor is a slab on ground, and ISO 13370 §9.3 applies.", why: "This is the parity brief's decision and is not reopened here, but the reader is owed the doubt: a Dutch kanaalplaat ground floor usually spans a ventilated kruipruimte, which is ISO 13370 §9.2, a different equation; and the model carries a '-1 fundering' datum at −1.00 m and an IFC_vloer_EPS_stortstrook edge detail, both consistent with either. ground-coupling.ts implements the slab case only and throws rather than approximating the others, so the choice is also the only one this repo can currently compute." },
    { id: "A-SOIL", assumes: "Soil conductivity 2.0 W/m·K under the slab.", why: "ISO 13370's own default when soil is unknown, and soil is never in a drawing set. It moves this ground U from 0.1553 (clay) to 0.1968 (rock); 0.1695 is the nominal. The slab area and exposed perimeter are measured now (345.81 m² / 90.08 m), so soil is the largest remaining uncertainty on this element after the slab-versus-crawlspace question in A-SUSPENDED-FLOOR." },
    { id: "A-LAYER-LAMBDAS", assumes: "Every λ behind these U-values is a mapping this repo chose, not a property the file states.", why: "The Schependomlaan IFC carries layer names and thicknesses and no IfcMaterialProperties at all — no conductivity, no U-value, no R. SCHEPENDOMLAAN_LAYER_MAPPINGS in constructions.ts names one generic-library material per Dutch layer name with the reason for each; that table, not the model, is where these numbers come from." },

    // ── Openings, systems, people ────────────────────────────────────────
    { id: "A-GLAZING", assumes: "Whole-window U 1.6 W/m²K, SHGC 0.60, HR++ double low-e in a hardwood frame.", why: "The file carries no IfcThermalTransmittance for its windows; it carries a frame profile, IFC_kozijn_90x114 in hardwood. Dutch 2015 HR++ GLASS is U_g 1.1-1.2, but the engine's field is the whole window: a hardwood frame at U_f near 2.0 over roughly a quarter of the opening, plus the spacer, lands U_w near 1.6. Quoting the glass figure here would credit the building with a frame it does not have. 1.6 sits just under the Bouwbesluit 2012 (2015 revision) window ceiling of 1.65, which is the only sourced bound available." },
    { id: "A-AIRTIGHT", assumes: "ACH50 = 2.05, converted from the NTA 8800 new-build default qv;10 = 0.6 dm³/s·m².", why: "No blower-door result exists for this building. The conversion is stated so it can be argued with: 0.6 × 965.67 m² = 579.4 L/s at 10 Pa; × 5^0.65 = 1,649 L/s at 50 Pa = 5,938 m³/h; ÷ 2,897.04 m³ = 2.05 h⁻¹, using the conventional pressure exponent n = 0.65. The engine then divides ACH50 by 20 to reach a natural rate of 0.102 h⁻¹, which is the divisor this repo's regression tests protect." },
    { id: "A-VOLUME", assumes: "The ventilation term uses the gross conditioned volume, 2,897.04 m³, not the 2,530.05 m³ the room solids sum to.", why: "The file states no volume; both figures are measured from it. The gross is floor area × storey floor-to-floor with voids as their own solids — everything inside the air barrier, which is what an infiltration rate is defined against. The net is the 100 space solids as modelled, which stop at the ceilings. Choosing the net would cut infiltration loss by 13 % for air that is inside the envelope." },
    { id: "A-HVAC", assumes: "Individual gas heating at η 0.90, no cooling, mechanical exhaust ventilation without heat recovery, gas DHW at η 0.85.", why: "The archive has no MEP model at all — measured, not assumed: HB_Nutsvoorzieningen.ifc is 42 IfcBuildingElementProxy utility connections with no IfcFlowSegment and no ports. So system type is not partly stated the way the Clinic's is; nothing about the services is stated. These are placeholders shaped like a 2015 Dutch apartment (HR combi boiler, system-C exhaust) and not one of them is read from the file. Cooling efficiency 0 is how annual-demand.ts is told a building has no cooling." },
    { id: "A-LPD", assumes: "Lighting power density 6 W/m², manual control, LED lamps.", why: "The file states no lighting load and no luminaire. Rather than invent a residential allowance, this takes the repo's own 공동주택 row (korean-building-codes.ts:176) so the building is not an outlier against every other residential model in the app — it is a Korean code-table value applied to a Dutch building, which is the same substitution A-CLIMATE makes and is stated the same way. The lamp type is forced by the enum: 2015 Dutch housing was mid-transition and neither 'fluorescent' nor 'led' describes it." },
    { id: "A-OCCUPANCY", assumes: "0.025 persons/m², residential day schedules, and the repo's own 공동주택 figures for internal gain (3) and hot water (40).", why: "No occupancy data exists in a coordination model, and the four fields split cleanly by whether anything reads them. Density IS read (delivered-from-demand.ts:41) and is therefore derived from what spaces.json states — 10 WOONKAMER, 10 KEUKEN, 10 BADKAMER and 10 MK rows make this ten dwellings — at 2.4 people each over 965.67 m², against the table's 0.04, which would put 3.9 people in a 96.6 m² Dutch flat. Internal gain and hot water are NOT read anywhere in src/lib/energy, and hotWaterDemand has no unit in material-types.ts at all, so both take the repo's own residential row rather than a derived figure whose unit this file would be inventing. The schedules are a generic dwelling shape: occupied overnight and at the ends of the day, the opposite of the Clinic's, which materially changes when gains land." },
    { id: "A-CLIMATE", assumes: "A Korean climate (Seoul) for a Dutch building.", why: "The town Nijmegen IS stated, on both IfcSite and IfcBuilding, so unlike the Clinic this building's location is not unknown — it is unusable. The engine's regional table is Korean-only and has no Netherlands entry, so any climate here is a substitution. A sourced Nijmegen HDD/CDD row from KNMI is the fix and is a follow-up, not this lane. Nijmegen is milder and duller than Seoul: Seoul's larger heating degree-days and far larger cooling degree-days both push this building's demand up." },

    // ── Scope and shape ──────────────────────────────────────────────────
    { id: "A-WALL-SET-SCOPE", assumes: "426.63 m² of inner-leaf exterior wall is the building's whole opaque wall.", why: "It may not be. 582.13 m² of gross wall over 12.00 m of height implies about 48.5 m of enclosing perimeter, and the measured slab outline is 90.08 m around — so either this is a terrace whose party walls are correctly excluded (the archive's YTONG-Kavel 01..10 files and the ten dwellings in spaces.json both point that way) or the extractor's exterior-wall walk missed part of the enclosure. The manifest itself records that 820 external space boundaries failed to resolve and that envelope areas come from the wall walk instead. The figure is used as measured and the tension is recorded rather than corrected." },
    { id: "A-ENVELOPE-ASSEMBLY-SET", assumes: "Twelve of the model's 28 assemblies are envelope: the roof panel, the dormer cheek, the ground floor and its edge strip, the three cavity-wall leaves and the window frame.", why: "The model does not label an assembly external, so the list in constructions.ts is hand-written and rests on bim-bf's identification of the cavity wall's leaves. IFC_kalkzandsteen appears in five thicknesses and only 100 and 120 mm are named as the exterior inner leaf; 175, 214 and 300 mm are excluded as internal and party walls, which the file does not state either. If that identification is wrong the envelope list is wrong with it. A keyword rule was rejected for the same reason: 'kalkzandsteen' would drag three interior walls onto the envelope, and the Clinic's own rule (exterior|roof|slab on grade|foundation) matches none of these Dutch names at all — applied here it returns an empty section, not a wrong one." },
    { id: "A-WALL-LEAVES-SHOWN-SEPARATELY", assumes: "The 외피 구성 section shows the cavity wall's three leaves at three separate U-values, not one wall at 0.2889.", why: "That is how the model states them, and constructions.ts solves only assemblies the model states. The insulation leaf alone reads about U 0.31, which is close to the whole wall's 0.29 by coincidence — 110 mm of glass wool is 92 % of the assembly's resistance — and a reader must not take either leaf's row for the wall. The composite is SCHEPENDOMLAAN_CAVITY_WALL in this file, where it is labelled an inference." },
    { id: "A-GROUND-ROW-IS-AIR-TO-AIR", assumes: "The ground floor's row in the 외피 구성 section reads U 0.2516, not the 0.1695 the energy path uses.", why: "That section reports what a layer stack resists between inside air and outside air, which is not what a floor on the ground does — the same split the Clinic shows, where its slab's row reads 3.873 against ISO 13370's 0.237. Here the gap is 1.5x rather than 16x because this floor is genuinely insulated, which makes it easier to miss, not less wrong. SCHEPENDOMLAAN_GROUND_FLOOR is the figure in the energy numbers; the section's row is the layer stack's own." },
    { id: "A-NORTH", assumes: "North is the model's −Z, and the wall split's four zero diagonals are real.", why: "TrueNorth is the schema default (0.,1.) in both representation contexts, so the model states no orientation. The manifest's own note claims all 122 inner-leaf walls are cardinal and that the 88 placements at 47.94° belong to the excluded outer leaf. That claim is the extractor's, not this file's, and every per-orientation figure here rests on it." },
    { id: "A-NO-FOOTPRINT", assumes: "The recipe's footprint is a 17.39 m square.", why: "The manifest states no plan outline and only 6 of the 100 IfcSpace rows carry an extent, so no bounding box can be recovered. The square has the ground storey's floor area and no relation to the building's shape. Nothing in the energy path reads it: measuredEnvelope short-circuits envelopeQuantities, which is the only reason a shape-free stand-in is admissible at all." },
    { id: "A-ENVELOPE-SOURCE", assumes: "Envelope areas come from the measured manifest and the placeholder table, not from the recipe's footprint.", why: "Extruding a square would produce 4 × 17.39 × 12.00 = 834 m² of wall against the 582.13 m² this building's own solids give, and a roof of 302.24 m² against the 542.96 m² of outer surface the rows measure. The areas travel on the recipe as measuredEnvelope and envelopeQuantities returns them with source 'measured'. Note what that source string does NOT mean today: three of those numbers — the glazing and door apertures inside grossWallSqm — are placeholders, and only SCHEPENDOMLAAN_INPUT_STATE says so." },
    { id: "A-ERA", assumes: "Era 2010-2019, use code 02000 (공동주택), structure code 22 (조적조).", why: "The archive's coordination models are dated 2015 and the project was built 2015-16, so the era is evidence. What it does NOT do is decide any number here: the era selects Korean code-table defaults for values not overridden, and every U-value, WWR and airtightness figure in this file is overridden explicitly, leaving the era's effect on cosmetic recipe fields only. The structure code is the nearest available: the register's vocabulary has no row for load-bearing calcium-silicate blockwork with precast hollow-core floors and a partial steel frame." },
  ]);
