import type { Command } from "@/lib/undo/types";
import { useComponentStore } from "@/store/component-store";
import type { PlacedComponent } from "@/lib/components/component-types";

/**
 * Places a component into the component store.
 * instanceId must be generated by the caller before constructing this command
 * so the same ID is used on re-execute (redo) — per UNDO_REDO.md pitfall 5.
 */
export class PlaceComponentCommand implements Command {
  readonly type = "place-component";

  constructor(
    private readonly pk: string,
    private readonly component: PlacedComponent
  ) {}

  execute(): void {
    useComponentStore.getState().placeComponent(this.pk, this.component);
  }

  undo(): void {
    useComponentStore.getState().removeComponent(this.pk, this.component.instanceId);
  }
}

/**
 * Removes a placed component from the store.
 * Stores the full component so it can be restored on undo.
 */
export class RemoveComponentCommand implements Command {
  readonly type = "remove-component";

  constructor(
    private readonly pk: string,
    private readonly component: PlacedComponent
  ) {}

  execute(): void {
    useComponentStore.getState().removeComponent(this.pk, this.component.instanceId);
  }

  undo(): void {
    useComponentStore.getState().placeComponent(this.pk, this.component);
  }
}

/**
 * Updates the position of a placed component.
 * Supports drag coalescing via update(): multiple position updates during a
 * single drag collapse into one undo step.
 */
export class UpdatePositionCommand implements Command {
  readonly type = "update-position";

  constructor(
    private readonly pk: string,
    private readonly instanceId: string,
    private readonly oldPos: [number, number, number],
    private newPos: [number, number, number]
  ) {}

  execute(): void {
    useComponentStore.getState().updatePosition(this.pk, this.instanceId, this.newPos);
  }

  undo(): void {
    useComponentStore.getState().updatePosition(this.pk, this.instanceId, this.oldPos);
  }

  update(newer: Command): boolean {
    if (
      newer instanceof UpdatePositionCommand &&
      newer.pk === this.pk &&
      newer.instanceId === this.instanceId
    ) {
      this.newPos = newer.newPos;
      return true;
    }
    return false;
  }
}
