import type { DiagnosisLocale } from "./types";

const ko = {
  title: "건물 에너지 진단",
  subtitle: "건물 모델의 근거를 확인하고, 검증한 입력으로 진단합니다.",
  referenceCase: "샘플 진단 시작",
  upload: "DXF 도면 업로드",
  replaceUpload: "새 도면 세트 검토",
  emptyTitle: "도면에서 진단까지, 한 흐름으로 시작하세요",
  emptyBody:
    "현재 지원되는 DXF 벡터 평면도로 시작하세요. BIMFIT이 해석한 경계와 모든 가정을 실행 전에 확인할 수 있습니다.",
  sourceDrawing: "원본 도면",
  modelView: "3D 에너지 모델",
  facts: "추출 근거",
  readiness: "모델 준비도",
  nextAction: "다음 권장 작업",
  preflight: "모델 검사",
  runBaseline: "기준안 시뮬레이션",
  runScenario: "대안 시뮬레이션",
  save: "프로젝트 저장",
  reload: "저장본 다시 열기",
  openRecent: "최근 저장 진단 열기",
  recentSaved: "최근 저장본",
  saved: "현재 모델·근거·실행 결과를 브라우저에 저장했습니다.",
  reloaded: "저장된 모델과 실행 결과를 복원했습니다.",
  noSaved: "이 프로젝트의 저장본이 없습니다.",
  loadingReference: "대표 도면을 분류하고 근거를 추출하는 중…",
  readingFiles: "파일을 검증하고 도면 세트를 구성하는 중…",
  running: "BIMFIT 실제 엔진을 실행하는 중…",
  noScene: "기존 BuildingScene 연결 지점",
  noSceneBody: "3D 뷰는 상위 Studio가 제공하며, 이 화면은 별도 장면을 만들지 않습니다.",
  annualEnergy: "연간 에너지",
  eui: "에너지사용집약도",
  heating: "난방",
  cooling: "냉방",
  lighting: "조명",
  equipment: "기기",
  annualEndUses: "연간 용도별 에너지",
  ratioEstimated: "비율 추정치(건물 용도)",
  endUseMethod:
    "단위·기간: kWh/yr · 방법: 난방·냉방은 도일 엔진, 조명·기기는 건물 용도별 고정 비율 추정치입니다.",
  affectedFacts: "영향받는 사실 ID",
  affectedObjects: "영향받는 객체 ID",
  baseline: "기준안",
  alternative: "개선 대안",
  scenarioHelp: "선택한 개선값만 변경하는 비파괴 대안입니다. 기준 모델의 도면 근거는 바뀌지 않습니다.",
  unsupportedTemporal: "현재 엔진은 월별·시간별·냉방피크를 계산하지 않아 빈 값으로 유지합니다.",
  areaApportioned: "열구역 값은 실제 전건물 결과를 면적으로 배분한 추정치입니다.",
  exactSource: "이 값은 어디에서 왔습니까?",
  sourceMissing: "연결된 도면 영역이 없습니다. 사용자 입력 또는 명시적 가정입니다.",
  confirmValue: "선택값 확인",
  applyAssumption: "0.5 ACH 가정 적용",
  assumptionExplanation:
    "기밀성 도면이 없어 자연환기 0.5 ACH를 프로젝트 가정으로 사용합니다. 언제든 되돌릴 수 있습니다.",
  resolveBeforeRun: "차단 항목을 먼저 해결해야 실제 엔진을 실행할 수 있습니다.",
  readyToRun: "검사 통과. 실제 엔진 입력을 생성할 수 있습니다.",
  noFabrication: "표시되지 않은 출력은 0이 아니라 ‘계산되지 않음’입니다.",
  calibratedWarning: "래스터 도면은 축척 근거가 없으면 형상 입력으로 사용할 수 없습니다.",
  selectedDocument: "선택 도면",
  sourceRegion: "근거 영역",
  confidence: "신뢰도",
  method: "추출 방식",
  revision: "리비전",
  tierEarly: "Tier 1 · 초기 설계 추정",
  tierDetailed: "Tier 2 · 상세 근거 포함",
  compareEmpty: "기준안을 실행한 뒤 창호 U값 대안을 비교할 수 있습니다.",
  scenarioValue: "대안 창호 U값",
  simulationFailed: "엔진 실행이 실패했습니다. 기존 모델과 근거는 안전하게 유지됩니다.",
  fileRejected: "일부 파일은 안전성 또는 형식 검증을 통과하지 못했습니다.",
  selectEvidence: "도면의 강조 영역이나 추출값을 선택하면 출처를 확인할 수 있습니다.",
} as const;

type DiagnosisCopy = { readonly [Key in keyof typeof ko]: string };

const en: DiagnosisCopy = {
  title: "Building Energy Diagnostic",
  subtitle: "Verify the building model, then diagnose it from traceable inputs.",
  referenceCase: "Start sample diagnostic",
  upload: "Upload DXF drawing",
  replaceUpload: "Review new drawing set",
  emptyTitle: "Move from drawings to diagnosis in one workflow",
  emptyBody:
    "Start with a supported DXF vector floor plan. Review every interpreted boundary and material assumption before the diagnostic runs.",
  sourceDrawing: "Source drawing",
  modelView: "3D energy model",
  facts: "Extracted evidence",
  readiness: "Model readiness",
  nextAction: "Recommended next action",
  preflight: "Model preflight",
  runBaseline: "Run baseline simulation",
  runScenario: "Run alternative",
  save: "Save project",
  reload: "Reload saved project",
  openRecent: "Open recent saved diagnosis",
  recentSaved: "Recent saved project",
  saved: "Saved the model, provenance, and exact runs in this browser.",
  reloaded: "Restored the saved model and simulation runs.",
  noSaved: "No saved copy exists for this project.",
  loadingReference: "Classifying the reference drawings and extracting evidence…",
  readingFiles: "Validating files and assembling the drawing set…",
  running: "Running the real BIMFIT engine…",
  noScene: "Existing BuildingScene integration slot",
  noSceneBody: "The parent Studio supplies 3D; this workflow does not create a separate scene.",
  annualEnergy: "Annual energy",
  eui: "Energy use intensity",
  heating: "Heating",
  cooling: "Cooling",
  lighting: "Lighting",
  equipment: "Equipment",
  annualEndUses: "Annual energy by end use",
  ratioEstimated: "Ratio-estimated (use type)",
  endUseMethod:
    "Unit/period: kWh/yr · Method: heating/cooling use the degree-day engine; lighting/equipment are fixed use-type ratio estimates.",
  affectedFacts: "Affected fact IDs",
  affectedObjects: "Affected object IDs",
  baseline: "Baseline",
  alternative: "Improvement alternative",
  scenarioHelp: "A non-destructive alternative changing only the values you set. Baseline drawing evidence remains untouched.",
  unsupportedTemporal: "The current engine does not calculate monthly, hourly, or cooling-peak outputs; they remain empty.",
  areaApportioned: "Zone values are area-apportioned estimates from the real whole-building result.",
  exactSource: "Where did this value come from?",
  sourceMissing: "No drawing region is linked. This is user input or an explicit assumption.",
  confirmValue: "Confirm selected value",
  applyAssumption: "Apply 0.5 ACH assumption",
  assumptionExplanation:
    "No airtightness drawing is present, so use 0.5 natural ACH as a reversible project assumption.",
  resolveBeforeRun: "Resolve blocking items before running the real engine.",
  readyToRun: "Preflight passed. The real engine input can be compiled.",
  noFabrication: "Unavailable outputs are not represented as valid zeros.",
  calibratedWarning: "Raster geometry cannot be used until a scale reference is confirmed.",
  selectedDocument: "Selected drawing",
  sourceRegion: "Evidence region",
  confidence: "Confidence",
  method: "Extraction method",
  revision: "Revision",
  tierEarly: "Tier 1 · early design estimate",
  tierDetailed: "Tier 2 · detailed evidence",
  compareEmpty: "Run the baseline before comparing a window U-value alternative.",
  scenarioValue: "Alternative window U-value",
  simulationFailed: "The engine run failed. The model and its evidence remain safe.",
  fileRejected: "Some files failed safety or format validation.",
  selectEvidence: "Select a highlighted drawing region or fact to inspect its origin.",
};

export function diagnosisCopy(locale: DiagnosisLocale) {
  return locale === "en" ? en : ko;
}
