// src/lib/rendering/material-library.ts
// Calibrated visual PBR catalog. Thermal λ/U live in energy-standards;
// these numbers are reflectance, roughness and real-world scale only.

import type { VisualMaterialId, VisualMaterialSpec } from "./types";
import { MATERIAL_ONTOLOGY } from "./material-ontology";
import { clampAlbedoHex, clampIor, clampMetalness, clampRoughness } from "./pbr-standards";

function spec(
  partial: Omit<VisualMaterialSpec, "nameKo" | "nameEn">,
): VisualMaterialSpec {
  const node = MATERIAL_ONTOLOGY.find((n) => n.id === partial.id);
  if (!node) throw new Error(`Library entry missing ontology node: ${partial.id}`);
  const metallic = partial.metalness >= 0.5;
  return {
    ...partial,
    nameKo: node.nameKo,
    nameEn: node.nameEn,
    albedo: clampAlbedoHex(partial.albedo, metallic),
    roughness: clampRoughness(partial.roughness),
    metalness: clampMetalness(partial.metalness),
    ior: clampIor(partial.ior),
  };
}

/**
 * Representative architectural materials. Albedos sit in physically
 * plausible bands (dielectric 4–94 %; metals ≥56 %). metresPerTile is the
 * real-world size of one albedo tile — brick is a 190×57 mm module sheet.
 */
export const MATERIAL_LIBRARY: readonly VisualMaterialSpec[] = Object.freeze([
  spec({
    id: "concrete-cast",
    family: "concrete",
    albedo: "#9a9790",
    roughness: 0.74,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [4.0, 4.0],
    textureSet: "concrete_rough",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.18, groundDirt: 0.14, oxidation: 0, fade: 0.06 },
    envMapIntensity: 0.55,
    microDetail: 0.7,
  }),
  spec({
    id: "concrete-precast",
    family: "concrete",
    albedo: "#b0ada6",
    roughness: 0.58,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.4, 1.2],
    textureSet: "concrete_clean",
    stochastic: "offset",
    weathering: { rainStreaks: 0.1, groundDirt: 0.08, oxidation: 0, fade: 0.04 },
    envMapIntensity: 0.65,
    microDetail: 0.55,
  }),
  spec({
    id: "concrete-polished",
    family: "concrete",
    albedo: "#c4c2bc",
    roughness: 0.28,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [3.0, 3.0],
    textureSet: "concrete_clean",
    stochastic: "offset",
    weathering: { rainStreaks: 0.04, groundDirt: 0.05, oxidation: 0, fade: 0.02 },
    envMapIntensity: 0.9,
    microDetail: 0.3,
  }),
  spec({
    id: "concrete-board-formed",
    family: "concrete",
    albedo: "#8f8b82",
    roughness: 0.8,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.4, 2.4],
    textureSet: "concrete_rough",
    stochastic: "offset",
    weathering: { rainStreaks: 0.22, groundDirt: 0.16, oxidation: 0, fade: 0.08 },
    envMapIntensity: 0.5,
    microDetail: 0.85,
  }),
  spec({
    id: "concrete-exposed-aggregate",
    family: "concrete",
    albedo: "#8a8680",
    roughness: 0.88,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1.5, 1.5],
    textureSet: "concrete_rough",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.12, groundDirt: 0.1, oxidation: 0, fade: 0.05 },
    envMapIntensity: 0.45,
    microDetail: 1,
  }),
  spec({
    id: "concrete-architectural",
    family: "concrete",
    albedo: "#b8b4ac",
    roughness: 0.62,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [3.0, 3.0],
    textureSet: "concrete_clean",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.12, groundDirt: 0.09, oxidation: 0, fade: 0.04 },
    envMapIntensity: 0.7,
    microDetail: 0.6,
  }),
  spec({
    id: "brick-red-clay",
    family: "brick",
    albedo: "#8a4a38",
    roughness: 0.84,
    metalness: 0,
    ior: 1.5,
    // ~8 running-bond bricks × 16 courses on the authored tile.
    metersPerTile: [1.68, 1.07],
    textureSet: "brick",
    stochastic: "offset",
    weathering: { rainStreaks: 0.14, groundDirt: 0.18, oxidation: 0, fade: 0.08 },
    envMapIntensity: 0.4,
    microDetail: 0.75,
  }),
  spec({
    id: "brick-brown-clay",
    family: "brick",
    albedo: "#6b4534",
    roughness: 0.86,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1.68, 1.07],
    textureSet: "brick",
    stochastic: "offset",
    weathering: { rainStreaks: 0.14, groundDirt: 0.18, oxidation: 0, fade: 0.08 },
    envMapIntensity: 0.4,
    microDetail: 0.75,
  }),
  spec({
    id: "brick-white",
    family: "brick",
    albedo: "#d4cfc6",
    roughness: 0.78,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1.68, 1.07],
    textureSet: "brick",
    stochastic: "offset",
    weathering: { rainStreaks: 0.16, groundDirt: 0.2, oxidation: 0, fade: 0.1 },
    envMapIntensity: 0.45,
    microDetail: 0.7,
  }),
  spec({
    id: "brick-weathered",
    family: "brick",
    albedo: "#7a5344",
    roughness: 0.9,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1.68, 1.07],
    textureSet: "brick",
    stochastic: "offset",
    weathering: { rainStreaks: 0.22, groundDirt: 0.24, oxidation: 0, fade: 0.14 },
    envMapIntensity: 0.35,
    microDetail: 0.85,
  }),
  spec({
    id: "brick-glazed",
    family: "brick",
    albedo: "#9a6a58",
    roughness: 0.28,
    metalness: 0,
    ior: 1.52,
    metersPerTile: [1.68, 1.07],
    textureSet: "brick",
    stochastic: "offset",
    weathering: { rainStreaks: 0.06, groundDirt: 0.08, oxidation: 0, fade: 0.03 },
    envMapIntensity: 0.95,
    microDetail: 0.35,
  }),
  spec({
    id: "stone-granite",
    family: "stone",
    albedo: "#8a8884",
    roughness: 0.55,
    metalness: 0,
    ior: 1.54,
    metersPerTile: [1.2, 1.2],
    textureSet: "concrete_rough",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.08, groundDirt: 0.1, oxidation: 0, fade: 0.03 },
    envMapIntensity: 0.7,
    microDetail: 0.65,
  }),
  spec({
    id: "stone-limestone",
    family: "stone",
    albedo: "#c8c2b4",
    roughness: 0.68,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1.5, 1.5],
    textureSet: "concrete_clean",
    stochastic: "offset",
    weathering: { rainStreaks: 0.1, groundDirt: 0.12, oxidation: 0, fade: 0.05 },
    envMapIntensity: 0.55,
    microDetail: 0.6,
  }),
  spec({
    id: "stone-marble",
    family: "stone",
    albedo: "#e6e2dc",
    roughness: 0.22,
    metalness: 0,
    ior: 1.56,
    metersPerTile: [1.8, 1.8],
    textureSet: "concrete_clean",
    stochastic: "offset",
    weathering: { rainStreaks: 0.04, groundDirt: 0.05, oxidation: 0, fade: 0.02 },
    envMapIntensity: 1.05,
    microDetail: 0.25,
  }),
  spec({
    id: "stone-sandstone",
    family: "stone",
    albedo: "#c4a882",
    roughness: 0.78,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1.4, 1.4],
    textureSet: "concrete_rough",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.12, groundDirt: 0.14, oxidation: 0, fade: 0.07 },
    envMapIntensity: 0.45,
    microDetail: 0.7,
  }),
  spec({
    id: "stone-slate",
    family: "stone",
    albedo: "#5a5c60",
    roughness: 0.5,
    metalness: 0,
    ior: 1.55,
    metersPerTile: [0.6, 0.6],
    textureSet: "roof_tile",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.08, oxidation: 0, fade: 0.04 },
    envMapIntensity: 0.65,
    microDetail: 0.55,
  }),
  spec({
    id: "metal-aluminum",
    family: "metal",
    albedo: "#c5c8cc",
    roughness: 0.28,
    metalness: 1,
    ior: 1.45,
    metersPerTile: [1.0, 1.0],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.06, groundDirt: 0.05, oxidation: 0.04, fade: 0.03 },
    envMapIntensity: 1.15,
    microDetail: 0.4,
  }),
  spec({
    id: "metal-stainless",
    family: "metal",
    albedo: "#c8ccd0",
    roughness: 0.18,
    metalness: 1,
    ior: 2.0,
    metersPerTile: [1.2, 1.2],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.04, groundDirt: 0.03, oxidation: 0.02, fade: 0.01 },
    envMapIntensity: 1.25,
    microDetail: 0.3,
  }),
  spec({
    id: "metal-galvanized",
    family: "metal",
    albedo: "#9aa09a",
    roughness: 0.42,
    metalness: 0.92,
    ior: 1.8,
    metersPerTile: [1.5, 1.5],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.06, oxidation: 0.1, fade: 0.04 },
    envMapIntensity: 1.0,
    microDetail: 0.5,
  }),
  spec({
    id: "metal-painted-steel",
    family: "metal",
    albedo: "#6a7078",
    roughness: 0.45,
    metalness: 0.18,
    ior: 1.5,
    metersPerTile: [1.2, 1.2],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.1, groundDirt: 0.08, oxidation: 0.06, fade: 0.08 },
    envMapIntensity: 0.75,
    microDetail: 0.45,
  }),
  spec({
    id: "metal-copper",
    family: "metal",
    albedo: "#b87333",
    roughness: 0.22,
    metalness: 1,
    ior: 1.1,
    metersPerTile: [1.0, 1.0],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.04, oxidation: 0.35, fade: 0.05 },
    envMapIntensity: 1.2,
    microDetail: 0.35,
  }),
  spec({
    id: "metal-zinc",
    family: "metal",
    albedo: "#9aa09c",
    roughness: 0.38,
    metalness: 0.95,
    ior: 1.1,
    metersPerTile: [1.2, 1.2],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.1, groundDirt: 0.06, oxidation: 0.12, fade: 0.04 },
    envMapIntensity: 1.05,
    microDetail: 0.4,
  }),
  spec({
    id: "metal-weathering-steel",
    family: "metal",
    albedo: "#8d4a2b",
    roughness: 0.58,
    metalness: 0.62,
    ior: 2.5,
    metersPerTile: [1.5, 1.5],
    textureSet: "metal_panel",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.16, groundDirt: 0.1, oxidation: 0.4, fade: 0.06 },
    envMapIntensity: 0.85,
    microDetail: 0.6,
  }),
  spec({
    id: "glass-clear",
    family: "glass",
    albedo: "#d5e0dc",
    roughness: 0.06,
    metalness: 0,
    ior: 1.52,
    metersPerTile: [1, 1],
    stochastic: "none",
    weathering: { rainStreaks: 0.04, groundDirt: 0.02, oxidation: 0, fade: 0 },
    glass: { opacity: 0.28, transmission: 0, envMapIntensity: 1.7 },
    envMapIntensity: 1.7,
    microDetail: 0.08,
  }),
  spec({
    id: "glass-low-e",
    family: "glass",
    albedo: "#c5d4d0",
    roughness: 0.05,
    metalness: 0,
    ior: 1.52,
    metersPerTile: [1, 1],
    stochastic: "none",
    weathering: { rainStreaks: 0.03, groundDirt: 0.02, oxidation: 0, fade: 0 },
    glass: { opacity: 0.34, transmission: 0, envMapIntensity: 1.85 },
    envMapIntensity: 1.85,
    microDetail: 0.06,
  }),
  spec({
    id: "glass-tinted",
    family: "glass",
    albedo: "#8aa39a",
    roughness: 0.07,
    metalness: 0,
    ior: 1.52,
    metersPerTile: [1, 1],
    stochastic: "none",
    weathering: { rainStreaks: 0.03, groundDirt: 0.02, oxidation: 0, fade: 0 },
    glass: { opacity: 0.42, transmission: 0, envMapIntensity: 1.6 },
    envMapIntensity: 1.6,
    microDetail: 0.08,
  }),
  spec({
    id: "glass-reflective",
    family: "glass",
    albedo: "#9bb0b8",
    roughness: 0.04,
    metalness: 0.08,
    ior: 1.52,
    metersPerTile: [1, 1],
    stochastic: "none",
    weathering: { rainStreaks: 0.02, groundDirt: 0.01, oxidation: 0, fade: 0 },
    glass: { opacity: 0.55, transmission: 0, envMapIntensity: 2.1 },
    envMapIntensity: 2.1,
    microDetail: 0.05,
  }),
  spec({
    id: "glass-frosted",
    family: "glass",
    albedo: "#d8ddd8",
    roughness: 0.42,
    metalness: 0,
    ior: 1.52,
    metersPerTile: [1, 1],
    stochastic: "none",
    weathering: { rainStreaks: 0.04, groundDirt: 0.03, oxidation: 0, fade: 0 },
    glass: { opacity: 0.72, transmission: 0, envMapIntensity: 0.9 },
    envMapIntensity: 0.9,
    microDetail: 0.2,
  }),
  spec({
    id: "glass-laminated",
    family: "glass",
    albedo: "#cfd8d4",
    roughness: 0.08,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [1, 1],
    stochastic: "none",
    weathering: { rainStreaks: 0.03, groundDirt: 0.02, oxidation: 0, fade: 0 },
    glass: { opacity: 0.36, transmission: 0, envMapIntensity: 1.55 },
    envMapIntensity: 1.55,
    microDetail: 0.1,
  }),
  spec({
    id: "wood-oak",
    family: "wood",
    albedo: "#8b5a2b",
    roughness: 0.62,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.0, 0.12],
    textureSet: "wood",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.1, oxidation: 0, fade: 0.1 },
    envMapIntensity: 0.45,
    microDetail: 0.55,
  }),
  spec({
    id: "wood-pine",
    family: "wood",
    albedo: "#c4a06a",
    roughness: 0.68,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.4, 0.14],
    textureSet: "wood",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.1, oxidation: 0, fade: 0.12 },
    envMapIntensity: 0.4,
    microDetail: 0.5,
  }),
  spec({
    id: "wood-cedar",
    family: "wood",
    albedo: "#a06040",
    roughness: 0.7,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.2, 0.14],
    textureSet: "wood",
    stochastic: "offset",
    weathering: { rainStreaks: 0.1, groundDirt: 0.12, oxidation: 0, fade: 0.14 },
    envMapIntensity: 0.4,
    microDetail: 0.55,
  }),
  spec({
    id: "wood-engineered",
    family: "wood",
    albedo: "#b08958",
    roughness: 0.5,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.4, 1.2],
    textureSet: "wood",
    stochastic: "offset",
    weathering: { rainStreaks: 0.04, groundDirt: 0.05, oxidation: 0, fade: 0.04 },
    envMapIntensity: 0.55,
    microDetail: 0.4,
  }),
  spec({
    id: "wood-exterior-weathered",
    family: "wood",
    albedo: "#7a6a58",
    roughness: 0.82,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.0, 0.14],
    textureSet: "wood",
    stochastic: "offset",
    weathering: { rainStreaks: 0.16, groundDirt: 0.18, oxidation: 0, fade: 0.2 },
    envMapIntensity: 0.35,
    microDetail: 0.7,
  }),
  spec({
    id: "roof-asphalt",
    family: "roof",
    albedo: "#4a4a4c",
    roughness: 0.9,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.0, 2.0],
    textureSet: "roof_flat",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.06, groundDirt: 0.08, oxidation: 0, fade: 0.12 },
    envMapIntensity: 0.35,
    microDetail: 0.7,
  }),
  spec({
    id: "roof-membrane",
    family: "roof",
    albedo: "#5a5c5e",
    roughness: 0.72,
    metalness: 0.05,
    ior: 1.5,
    metersPerTile: [4.0, 4.0],
    textureSet: "roof_flat",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.05, groundDirt: 0.06, oxidation: 0.04, fade: 0.1 },
    envMapIntensity: 0.5,
    microDetail: 0.45,
  }),
  spec({
    id: "roof-clay-tile",
    family: "roof",
    albedo: "#8a4a3a",
    roughness: 0.7,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [0.8, 0.4],
    textureSet: "roof_tile",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.08, oxidation: 0, fade: 0.1 },
    envMapIntensity: 0.45,
    microDetail: 0.65,
  }),
  spec({
    id: "roof-concrete-tile",
    family: "roof",
    albedo: "#8a8680",
    roughness: 0.78,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [0.84, 0.42],
    textureSet: "roof_tile",
    stochastic: "offset",
    weathering: { rainStreaks: 0.1, groundDirt: 0.08, oxidation: 0, fade: 0.08 },
    envMapIntensity: 0.4,
    microDetail: 0.65,
  }),
  spec({
    id: "roof-standing-seam",
    family: "roof",
    albedo: "#6e747c",
    roughness: 0.35,
    metalness: 0.55,
    ior: 1.5,
    metersPerTile: [0.45, 3.0],
    textureSet: "metal_panel",
    stochastic: "offset",
    weathering: { rainStreaks: 0.08, groundDirt: 0.04, oxidation: 0.08, fade: 0.06 },
    envMapIntensity: 1.0,
    microDetail: 0.4,
  }),
  spec({
    id: "roof-green",
    family: "roof",
    albedo: "#4a6a3a",
    roughness: 0.92,
    metalness: 0,
    ior: 1.4,
    metersPerTile: [3.0, 3.0],
    stochastic: "rotate",
    weathering: { rainStreaks: 0.04, groundDirt: 0.06, oxidation: 0, fade: 0.05 },
    envMapIntensity: 0.25,
    microDetail: 0.8,
  }),
  spec({
    id: "ground-asphalt",
    family: "ground",
    albedo: "#3d3d40",
    roughness: 0.92,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [8.0, 8.0],
    textureSet: "concrete_rough",
    stochastic: "rotate",
    weathering: { rainStreaks: 0, groundDirt: 0.08, oxidation: 0, fade: 0.1 },
    envMapIntensity: 0.3,
    microDetail: 0.75,
  }),
  spec({
    id: "ground-concrete-pavement",
    family: "ground",
    albedo: "#9a9892",
    roughness: 0.82,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [3.0, 3.0],
    textureSet: "concrete_clean",
    stochastic: "offset",
    weathering: { rainStreaks: 0.04, groundDirt: 0.12, oxidation: 0, fade: 0.06 },
    envMapIntensity: 0.4,
    microDetail: 0.55,
  }),
  spec({
    id: "ground-paver",
    family: "ground",
    albedo: "#8a8074",
    roughness: 0.8,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [0.6, 0.3],
    textureSet: "concrete_rough",
    stochastic: "offset",
    weathering: { rainStreaks: 0.02, groundDirt: 0.14, oxidation: 0, fade: 0.08 },
    envMapIntensity: 0.35,
    microDetail: 0.6,
  }),
  spec({
    id: "ground-gravel",
    family: "ground",
    albedo: "#8a8478",
    roughness: 0.95,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [2.0, 2.0],
    textureSet: "concrete_rough",
    stochastic: "rotate",
    weathering: { rainStreaks: 0, groundDirt: 0.06, oxidation: 0, fade: 0.04 },
    envMapIntensity: 0.25,
    microDetail: 0.9,
  }),
  spec({
    id: "ground-soil",
    family: "ground",
    albedo: "#5a4634",
    roughness: 0.95,
    metalness: 0,
    ior: 1.4,
    metersPerTile: [6.0, 6.0],
    stochastic: "rotate",
    weathering: { rainStreaks: 0, groundDirt: 0.04, oxidation: 0, fade: 0.02 },
    envMapIntensity: 0.2,
    microDetail: 0.7,
  }),
  spec({
    id: "ground-grass",
    family: "ground",
    albedo: "#3a5c28",
    roughness: 0.9,
    metalness: 0,
    ior: 1.4,
    metersPerTile: [8.0, 8.0],
    stochastic: "rotate",
    weathering: { rainStreaks: 0, groundDirt: 0.05, oxidation: 0, fade: 0.04 },
    envMapIntensity: 0.22,
    microDetail: 0.8,
  }),
  spec({
    id: "paint-stucco",
    family: "paint",
    albedo: "#d4cfc4",
    roughness: 0.72,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [3.0, 3.0],
    textureSet: "concrete_clean",
    stochastic: "rotate",
    weathering: { rainStreaks: 0.2, groundDirt: 0.16, oxidation: 0, fade: 0.12 },
    envMapIntensity: 0.45,
    microDetail: 0.5,
  }),
  spec({
    id: "interior-cavity",
    family: "paint",
    albedo: "#1c1914",
    roughness: 0.95,
    metalness: 0,
    ior: 1.5,
    metersPerTile: [4.0, 4.0],
    stochastic: "none",
    weathering: { rainStreaks: 0, groundDirt: 0, oxidation: 0, fade: 0 },
    envMapIntensity: 0.12,
    microDetail: 0.1,
  }),
]);

const BY_ID = new Map(MATERIAL_LIBRARY.map((s) => [s.id, s]));

export function getVisualMaterial(id: VisualMaterialId): VisualMaterialSpec {
  const spec = BY_ID.get(id);
  if (!spec) throw new Error(`Unknown visual material: ${id}`);
  return spec;
}

export function tryGetVisualMaterial(id: string | undefined): VisualMaterialSpec | null {
  if (!id) return null;
  return BY_ID.get(id as VisualMaterialId) ?? null;
}
