export const landingCopy = {
  ko: {
    skip: "본문으로 건너뛰기",
    brand: "BIMFIT",
    h1: "BIMFIT",
    heroPhrase: "BIMFIT: Building Energy Retrofit Simulator",
    version: "v0.1.0",
    titleKo: "구상에서 트윈까지",
    titleEn: "Concept to Twin",
    display: "구상에서 트윈까지",
    sheet: "A-01",
    scale: "1 : 200",
    lead: "문장으로 설명하거나 도면을 그리면, 그 건물의 3D 트윈이 만들어집니다.",
    leadSecondary: "에너지와 그린리모델링 투자 답이 같은 건물에서 나옵니다. 데모부터 둘러보세요.",
    workflowLabel: "작업 흐름",
    workflowValue: "4단계",
    startLabel: "첫 방문",
    startValue: "키 없이 데모",
    answerLabel: "같은 건물에서",
    answerValue: "에너지 · 투자 답",
    revealTitle: "그 건물의 3D 트윈",
    studio: "도면 그려서 만들기",
    studioSub: "Draw a floor plan",
    importDrawing: "도면 가져오기",
    importDrawingSub: "Import a drawing",
    demo: "데모 건물 둘러보기",
    tensionLeft: "대장만",
    tensionRight: "트윈",
    tensionVoid: "트윈 없음",
    tensionHint: "대장은 도장입니다. 선을 눌러 트윈을 올리세요.",
    revealDrag: "드래그해서 돌리기 · 스페이스로 층 펼치기",
    revealExplode: "층 펼치기",
    revealFold: "층 접기",
    hoverHint: "선을 누르면 트윈이 일어납니다.",
    layerRail: "레이어",
    layerHint: "레이어가 스스로 바뀝니다",
    layers: {
      rendered: { name: "렌더", caption: "벽돌 외피 · 창호 · 처마" },
      structure: { name: "구조", caption: "슬래브 · 기둥 · 코어" },
      mechanical: { name: "기계", caption: "층마다 덕트 · 배관 · 전기" },
      all: { name: "전체", caption: "외피 · 골조 · 설비가 같은 건물" },
    },
    stages: [
      {
        id: "search",
        no: "01",
        title: "건물 검색",
        body: "시·군·구와 법정동, 또는 지번으로 실제 건축물대장을 찾습니다.",
        href: "lookup",
        action: "조회 열기",
      },
      {
        id: "upload",
        no: "02",
        title: "도면 업로드",
        body: "DXF·DWG·PDF를 올리거나 브라우저에서 평면을 그립니다. 그 선이 발자국이 됩니다.",
        href: "cad",
        action: "도면으로 시작",
      },
      {
        id: "twin",
        no: "03",
        title: "디지털 트윈",
        body: "돌려보고 예산을 움직이면 에너지와 투자 숫자가 같이 바뀝니다.",
        href: "demo",
        action: "데모 트윈 열기",
      },
      {
        id: "report",
        no: "04",
        title: "보고서",
        body: "에너지 감사와 그린리모델링 답을 PDF·CSV·JSON으로 가져갑니다.",
        href: "demo",
        action: "데모에서 보기",
      },
    ],
    // These four are no longer wired to any landing door (the ledger-search
    // instrument they belong to was quarantined — see landing-page.tsx) but
    // stay defined so the still-present, not-yet-deleted lookup-instrument.tsx
    // keeps type-checking until a future removal pass deletes it outright.
    lookupTitle: "건물 조회",
    lookupLead:
      "지역 또는 주소로 건축물대장을 찾습니다. 캠퍼스는 한 법정동을 묶습니다. 에너지 숫자는 트윈을 연 뒤에 나옵니다.",
    campus: "캠퍼스 모드",
    campusOn: "캠퍼스 모드 ON",
    campusOff: "캠퍼스 모드 OFF",
    apiMissing: "API 키가 설정되지 않았습니다.",
    apiMissingBody:
      "실제 건물을 검색하려면 오른쪽 위 열쇠로 API 키를 설정하세요. 데모는 키 없이 됩니다.",
    drawingLabel: "입면도 · 평면도 — 데모 오피스, 업무시설, 지상 10층",
    switchToEn: "Switch to English",
    switchToKo: "한국어로 전환",
  },
  en: {
    skip: "Skip to content",
    brand: "BIMFIT",
    h1: "BIMFIT",
    heroPhrase: "BIMFIT: Building Energy Retrofit Simulator",
    version: "v0.1.0",
    titleKo: "구상에서 트윈까지",
    titleEn: "Concept to Twin",
    display: "Concept to Twin",
    sheet: "A-01",
    scale: "1 : 200",
    lead: "Describe a building in a sentence, or draw it — either becomes its 3D twin.",
    leadSecondary:
      "Energy and the green-remodeling answer come from that same building. Start with the demo.",
    workflowLabel: "Workflow",
    workflowValue: "4 stages",
    startLabel: "First visit",
    startValue: "Demo, no key",
    answerLabel: "Same building",
    answerValue: "Energy · investment",
    revealTitle: "그 건물의 3D 트윈",
    studio: "Draw a floor plan",
    studioSub: "도면 그려서 만들기",
    importDrawing: "Import a drawing",
    importDrawingSub: "도면 가져오기",
    demo: "Explore the demo building",
    tensionLeft: "Ledger only",
    tensionRight: "Twin",
    tensionVoid: "No twin",
    tensionHint: "The ledger is a stamp. Press the lines to raise the twin.",
    revealDrag: "Drag to orbit · Space to peel floors",
    revealExplode: "Peel floors",
    revealFold: "Stack floors",
    hoverHint: "Press the lines to raise the twin.",
    layerRail: "Layers",
    layerHint: "Layers peel on their own",
    layers: {
      rendered: { name: "Rendered", caption: "Brick, punched windows, cornice" },
      structure: { name: "Structure", caption: "Slabs · columns · core" },
      mechanical: { name: "Mechanical", caption: "Ducts, pipe, power on every floor" },
      all: { name: "All", caption: "Envelope, frame, and plant of one building" },
    },
    stages: [
      {
        id: "search",
        no: "01",
        title: "Search",
        body: "Find a real ledger by district and dong, or by lot number.",
        href: "lookup",
        action: "Open lookup",
      },
      {
        id: "upload",
        no: "02",
        title: "Upload CAD",
        body: "Upload DXF, DWG, or PDF, or draw a plan. Those lines become the footprint.",
        href: "cad",
        action: "Start from a drawing",
      },
      {
        id: "twin",
        no: "03",
        title: "Twin",
        body: "Rotate the model. Move the budget and energy and investment move with it.",
        href: "demo",
        action: "Open the demo twin",
      },
      {
        id: "report",
        no: "04",
        title: "Report",
        body: "Take the energy audit and the investment answer as PDF, CSV, or JSON.",
        href: "demo",
        action: "See it on the demo",
      },
    ],
    // See the matching ko-block comment: kept only for lookup-instrument.tsx.
    lookupTitle: "Look up a ledger",
    lookupLead:
      "Find a ledger by region or address. Campus batches one dong. Energy numbers appear after a twin exists.",
    campus: "Campus mode",
    campusOn: "Campus mode ON",
    campusOff: "Campus mode OFF",
    apiMissing: "No API key configured.",
    apiMissingBody:
      "To search real buildings, set your API key via the key icon. The demo works without one.",
    drawingLabel: "Elevation · plan — demo office, 10 floors above grade",
    switchToEn: "Switch to English",
    switchToKo: "한국어로 전환",
  },
} as const;

export type LandingLang = keyof typeof landingCopy;
export type LandingCopy = (typeof landingCopy)[LandingLang];
