export const landingCopy = {
  ko: {
    skip: "본문으로 건너뛰기",
    issue: "건축 저널",
    pageNo: "001",
    kickerPlan: "01  PLAN",
    kickerCost: "02  COST",
    kickerTwin: "03  TWIN",
    kickerMethod: "04  METHOD",
    kickerBegin: "05  BEGIN",
    brand: "BIMFIT",
    titleEn: "Ledger to Twin",
    titleKo: "대장에서 트윈까지",
    h1: "BIMFIT",
    lead: "건축물대장 또는 도면을 넣으면, 그 건물의 3D 트윈이 열립니다. 에너지 숫자와 그린리모델링 투자 답이 같은 건물에서 나옵니다.",
    leadSecondary:
      "Revit도 ECO2도 없이. 키 없이 데모 오피스를 먼저 돌릴 수 있습니다.",
    demo: "데모 건물 둘러보기",
    cad: "CAD 도면으로 시작하기",
    lookupJump: "지역·주소 검색",
    demoHint:
      "키 없이 데모 오피스의 트윈과 투자 숫자를 보거나, DXF·DWG를 올리거나 브라우저에서 도면을 그려 시작하세요.",
    photoCaption:
      "데모 오피스 타워 — 강남 업무시설, 2008, 지상 10층 / 지하 2층. 대장에서 만든 3D 트윈.",
    spec: [
      { k: "시작", v: "키 없이 데모" },
      { k: "보기", v: "3D 트윈" },
      { k: "숫자", v: "에너지 · NPV" },
      { k: "가져가기", v: "보고서 · CSV" },
    ],
    tensionTitle: "대장은 종이입니다",
    tensionTitleEn: "The ledger is still paper",
    tensionLead:
      "Revit. ECO2. 공공포털. 세 도구를 켜도 그 건물은 아직 보이지 않습니다. 표제부를 찾았는데 층이 안 열리고, 에너지 등급은 비어 있고, 그린리모델링 예산은 감으로 남습니다.",
    tensionLeft: "대장만",
    tensionRight: "트윈 없음",
    tensionVoid: "아직 건물이 없습니다",
    tensionHint: "밀어 비교하세요. 화살표 키도 됩니다.",
    revealTitle: "그 건물의 3D 트윈",
    revealTitleEn: "The twin of that building",
    revealLead:
      "데모 오피스의 간이 매싱입니다. 드래그해서 돌리고, 스페이스로 층을 펼치세요. 본 트윈 — 에너지와 투자 숫자 — 은 안에서 열립니다.",
    revealDrag: "드래그해서 돌리기",
    revealExplode: "층 펼치기",
    revealFold: "층 접기",
    revealOpen: "이 트윈 열기",
    proofTitle: "네 단계입니다",
    proofTitleEn: "Four stages, one building",
    proofLead:
      "검색에서 보고서로. 단계는 네 개뿐입니다. 고르면 그 단계가 하는 일이 열립니다.",
    stages: [
      {
        id: "search",
        no: "01",
        title: "건물 검색",
        body: "시·군·구와 법정동, 또는 지번으로 실제 건축물대장을 찾습니다. 주용도는 받은 뒤에 거릅니다.",
        action: "조회로 내려가기",
        href: "#lookup",
      },
      {
        id: "upload",
        no: "02",
        title: "도면 업로드",
        body: "DXF·DWG·PDF를 올리거나 브라우저에서 평면을 그립니다. 그 선이 트윈의 발자국이 됩니다.",
        action: "도면으로 시작",
        href: "cad",
      },
      {
        id: "twin",
        no: "03",
        title: "디지털 트윈",
        body: "돌려보고, 아래 예산을 움직이면 에너지와 투자 숫자가 같이 바뀝니다. 같은 건물입니다.",
        action: "데모 트윈 열기",
        href: "demo",
      },
      {
        id: "report",
        no: "04",
        title: "보고서",
        body: "에너지 감사와 그린리모델링 답을 PDF·CSV·JSON으로 가져갑니다. 내일 같은 건물을 다시 엽니다.",
        action: "데모에서 보기",
        href: "demo",
      },
    ],
    inviteTitle: "키 없이 시작하세요",
    inviteTitleEn: "Begin without a key",
    inviteLead:
      "데모 오피스를 돌리거나, 도면을 올리거나, 키가 있으면 실제 대장을 찾습니다. 캠퍼스는 한 법정동을 묶습니다.",
    lookupTitle: "건물 조회",
    lookupTitleEn: "Look up a ledger",
    lookupLead:
      "지역 또는 주소로 건축물대장을 찾습니다. 캠퍼스 모드는 한 법정동의 목록을 한 번에 불러옵니다. 에너지 숫자는 트윈을 연 뒤에 나옵니다.",
    campus: "캠퍼스 모드",
    campusOn: "캠퍼스 모드 ON",
    campusOff: "캠퍼스 모드 OFF",
    apiMissing: "API 키가 설정되지 않았습니다.",
    apiMissingBody:
      "실제 건물을 검색하려면 오른쪽 위 열쇠로 API 키를 설정하세요. 데모 건물은 키 없이 이용할 수 있습니다.",
    stickyLabel: "BIMFIT",
    footerNote: "한국 건축물대장 · 3D 트윈 · 그린리모델링",
    scale: "0  10m",
  },
  en: {
    skip: "Skip to content",
    issue: "Architecture journal",
    pageNo: "001",
    kickerPlan: "01  PLAN",
    kickerCost: "02  COST",
    kickerTwin: "03  TWIN",
    kickerMethod: "04  METHOD",
    kickerBegin: "05  BEGIN",
    brand: "BIMFIT",
    titleEn: "Ledger to Twin",
    titleKo: "대장에서 트윈까지",
    h1: "BIMFIT",
    lead: "Open a 3D twin from a ledger or a drawing, then see the energy and green-remodeling investment answer.",
    leadSecondary:
      "No Revit. No ECO2. The demo office opens without an API key.",
    demo: "Explore the demo building",
    cad: "Start from a CAD drawing",
    lookupJump: "Search by region or address",
    demoHint:
      "No API key needed — open the demo office twin and its investment numbers, or start from a DXF/DWG or a plan you draw in the browser.",
    photoCaption:
      "Demo office tower — Gangnam office use, 2008, 10F / B2. A 3D twin grown from the ledger.",
    spec: [
      { k: "Start", v: "Demo, no key" },
      { k: "See", v: "3D twin" },
      { k: "Number", v: "Energy · NPV" },
      { k: "Leave with", v: "Report · CSV" },
    ],
    tensionTitle: "The ledger is still paper",
    tensionTitleEn: "대장은 종이입니다",
    tensionLead:
      "Revit. ECO2. The public portal. Three tools, and the building is still invisible. You found the title record. The floors will not open. The energy grade is empty. The green-remodeling budget is a guess.",
    tensionLeft: "Ledger only",
    tensionRight: "No twin",
    tensionVoid: "There is no building yet",
    tensionHint: "Drag to compare. Arrow keys work too.",
    revealTitle: "The twin of that building",
    revealTitleEn: "그 건물의 3D 트윈",
    revealLead:
      "A massing of the demo office. Drag to orbit. Space to peel the floors. The full twin — energy and investment — opens inside.",
    revealDrag: "Drag to orbit",
    revealExplode: "Peel floors",
    revealFold: "Stack floors",
    revealOpen: "Open this twin",
    proofTitle: "Four stages, one building",
    proofTitleEn: "네 단계입니다",
    proofLead:
      "Search to report. Only four stages. Pick one to see what it does.",
    stages: [
      {
        id: "search",
        no: "01",
        title: "Search",
        body: "Find a real ledger by district and dong, or by lot number. Use type is filtered after the fetch.",
        action: "Jump to lookup",
        href: "#lookup",
      },
      {
        id: "upload",
        no: "02",
        title: "Upload CAD",
        body: "Upload DXF, DWG, or PDF, or draw a plan in the browser. Those lines become the twin’s footprint.",
        action: "Start from a drawing",
        href: "cad",
      },
      {
        id: "twin",
        no: "03",
        title: "Twin",
        body: "Rotate the model. Move the budget and the energy and investment numbers move with it. Same building.",
        action: "Open the demo twin",
        href: "demo",
      },
      {
        id: "report",
        no: "04",
        title: "Report",
        body: "Take the energy audit and the investment answer as PDF, CSV, or JSON. Open the same building tomorrow.",
        action: "See it on the demo",
        href: "demo",
      },
    ],
    inviteTitle: "Begin without a key",
    inviteTitleEn: "키 없이 시작하세요",
    inviteLead:
      "Orbit the demo office, upload a drawing, or — with a key — look up a real ledger. Campus batches one dong.",
    lookupTitle: "Look up a ledger",
    lookupTitleEn: "건물 조회",
    lookupLead:
      "Find a building ledger by region or address. Campus mode loads one dong at a time. Energy numbers appear after a twin exists.",
    campus: "Campus mode",
    campusOn: "Campus mode ON",
    campusOff: "Campus mode OFF",
    apiMissing: "No API key configured.",
    apiMissingBody:
      "To search real buildings, set your API key via the key icon in the top-right. The demo building works without one.",
    stickyLabel: "BIMFIT",
    footerNote: "Korean building ledger · 3D twin · green remodeling",
    scale: "0  10m",
  },
} as const;

export type LandingLang = keyof typeof landingCopy;
export type LandingCopy = (typeof landingCopy)[LandingLang];
